### PR TITLE
HelmChartInflationGenerator: inherit environment variables to helm command

### LINKED ISSUE #3712: HelmChartInflationGenerator + HTTP_PROXY
**Describe the bug**

If HelmChartInflationGenerator is used, kustomize do not pass environment variables to the helm command.

If HTTP_PROXY is defined and required, helm pull will fail because the env var HTTP_PROXY is not passed to the helm pull command.

**Files that can reproduce the issue**

*Note:* Since not everything has a forwarded proxy at home, i'm provide an example that should fail.

Example:

kustomization.yaml

```
namespace: monitoring-application
generators:
  - kube-prometheus-stack.yaml
```

kube-prometheus-stack.yaml

```
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: notImportantHere
chartName: kube-prometheus-stack
chartRepoUrl: https://prometheus-community.github.io/helm-charts
chartVerion: 13.13.1
```

```
env http_proxy=http://invalid https_proxy=http://invalid kustomize build
```

**Expected output**

```
Error: looks like "https://prometheus-community.github.io/helm-charts" is not a valid chart repository or cannot be reached: Get "https://prometheus-community.github.io/helm-charts/index.yaml": proxyconnect tcp: dial tcp: lookup invalid: no such host
```

Got this from:

```
env https_proxy=http://invalid http_proxy=http://invalid helm pull --untar --untardir /tmp/kustomize-769873136/chart --repo https://prometheus-community.github.io/helm-charts kube-prometheus-stack
```

**Actual output**

Everything works.

**Kustomize version**

* 3.9.4
* 4.0.4

**Platform**

* Linux
* MacOS

**Additional context**

I want to use `HelmChartInflationGenerator` inside a ArgoCD environment, but the ArgoCD needs a proxy for internet connection.

### PR DESCRIPTION
**Pull request by jkroepke**
Fixes #3712 

Taking this code fragment from the example here: https://golang.org/pkg/os/exec/#Command

Let me know if I forgot something. Not doing golang contribution every day.

### CODE REVIEW

**Comment by Shell32-Natsu** [comment]
Thanks for the PR!

You need to update `plugin/builtin/helmchartinflationgenerator/HelmChartInflationGenerator.go` and then generate the builtin plugin. Plus I don't see the actual test code.

**Comment by jkroepke** [comment]
How I could do this?

```
jkr@joe-nb kustomize % make generate-kustomize-builtin-plugins
generating ConfigMapGenerator
( \
                set -e; \
                cd plugin/builtin/configmapgenerator; \
                go generate .; \
                cd ../../../api/builtins; \
                /Users/jkr/go/bin/goimports -w ConfigMapGenerator.go \
        )
bash: /Users/jkr/go/bin/goimports: No such file or directory
make: *** [api/builtins/ConfigMapGenerator.go] Error 1


jkr@joe-nb kustomize % make install-tools                     
cd api; \
        go install golang.org/x/tools/cmd/goimports
missing go.sum entry for module providing package golang.org/x/tools/cmd/goimports; to add:
        go mod download golang.org/x/tools
make: *** [/Users/jkr/go/bin/goimports] Error 1

```

**Comment by jkroepke** [comment]
@Shell32-Natsu is it possible to backport this into kustomize 3? (for 3.9? since ArgoCD is using kustomize 3.9)

**Pull request merged**
