### PR TITLE
handle the "$patch: delete" in patch transformer

### LINKED ISSUE #2945: $patch: delete on an object results: Error: Object 'Kind' is missing in '{}'
`$patch: delete` on an object results:
```
Error: Object 'Kind' is missing in '{}'
```

Example
workloads.yaml:
```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp1
  name: myapp1
spec:
  ports:
  - port: 80
  selector:
    app: myapp1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp2
  name: myapp2
spec:
  ports:
  - port: 80
  selector:
    app: myapp2
```

kustomization.yaml:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- workloads.yaml
patches:
- patch: |
    apiVersion: v1
    kind: Service
    metadata:
      name: myapp1
    $patch: delete
  target:
    kind: Service
    name: myapp1
```

Execution:
```
$ kustomize build
Error: Object 'Kind' is missing in '{}'
```

It should work according to https://github.com/kubernetes-sigs/kustomize/issues/1384#issuecomment-514775221

### PR DESCRIPTION
**Pull request by Shell32-Natsu**
fix #2945 

Use the same hack in PatchStrategicMergeTransformer.go

### CODE REVIEW

**Comment by Shell32-Natsu** [comment]
> @Shell32-Natsu: PR needs rebase.
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

https://github.com/kubernetes-sigs/kustomize/pull/3001#issuecomment-694796618

We have another bot now lol

**Comment by monopole** [comment]
Needs a rebase, but looks good to me.

The goal here should be to use just one plugin, configured via various means (the various patch directives in kustomization.yaml), rather than duplicate all this tricky code.

**Comment by monopole** [comment]
The rebase just unpins a bunch of intra-module dependencies, which is the state we want to be in until the next release.

**Comment by Shell32-Natsu** [comment]
> Needs a rebase, but looks good to me.
> 
> The goal here should be to use just one plugin, configured via various means (the various patch directives in kustomization.yaml), rather than duplicate all this tricky code.

I suppose that kyaml should be able to handle removal of resource so we don't need to have these hacks.

**Comment by monopole** [comment]
That's up to the maintainers of kyaml :)

**Pull request merged**
