### PR TITLE
Add gometalinter to pre-commit hook

### PR DESCRIPTION
**Pull request by uthark**
Work in progress for #100.

Do not merge so far.

### CODE REVIEW

**Comment by Liujingfang1** [comment]
@uthark Is this ready for review?

**Comment by uthark** [comment]
Please see ticket, I would like to add additional linters in separatePRs, if you ok with it.

**Comment by Liujingfang1** [comment]
Can you squash the commits?

**Comment by uthark** [comment]
Sure, no problem. I thought @monopole wanted them separately. 

Regards,
Oleg.

**Pull request merged**
