### PR TITLE
Fix IsFieldEmpty in cmdxargs

### PR DESCRIPTION
**Pull request by Shell32-Natsu**

### CODE REVIEW

**Comment by Shell32-Natsu** [comment]
Did a grep search again and I think there is no other invocation to `IsFieldEmpty` in kustomize repo.

**Comment by monopole** [comment]
OK, looks like the longer route is the way to go.
First make the code change (in this PR).
Then change `cmd/config/go.mod` in another PR

**Comment by Shell32-Natsu** [comment]
I forget to update go.mod in kustomize

**Comment by monopole** [comment]
It's just cleaner to keep go.mod changes and code changes in distinct prs.

**Comment by Shell32-Natsu** [comment]
Updated the go.mod before I saw the comment. Will try to separate them in future.

**Pull request merged**
