### PR TITLE
update kyaml's dependency swag to v0.22.3

### PR DESCRIPTION
**Pull request by summer-dev**
kyaml now depends on swag v0.19.14 which itself depends on https://github.com/niemeyer/pretty, this pretty package is a fork 

of  https://github.com/kr/pretty, the previous pretty is out of date,while the latter is maintained well,

swag v0.22.3 has already updated its dependency to kr's, I think it's necessary to  update kyaml's too

thanks.

### CODE REVIEW

**Comment by natasha41575** [comment]
Please sign the CLA

**Comment by summer-dev** [comment]
> Please sign the CLA

Done,thanks for your remind :)

**Comment by summer-dev** [comment]
Thanks for your review @mengqiy  @phanimarupaka

**Comment by summer-dev** [comment]
@natasha41575 

dear natasha41575 : 

i'm confused about the failure reason of  this sute  : test-unit-non-plugin, it seems that some missed files are needed during testing.

image

i wonder where i  can get  these missed files? how can I solve this problem,

thanks

**Comment by koba1t** [comment]
Hi @summer-dev
That CI failure is caused by changing environment on GitHub Actions and that was fixed at https://github.com/kubernetes-sigs/kustomize/pull/4844.
So, Could you try to `rebase master`?

**Comment by summer-dev** [comment]
i wish another LGTM gift :)

**Comment by koba1t** [comment]
Thanks, @summer-dev !
Please update libs for other places using a function of go workspace mode.
That will work by typing the command to `go work sync`!

/assign koba1t

**Comment by summer-dev** [comment]
> 

Hi, after executing
```
go work sync
```
About 90 files are modified, should I commit theses changes to my forked repo? and then waiting  to be merged.

**Comment by koba1t** [comment]
> About 90 files are modified, should I commit theses changes to my forked repo?

Thanks! Please commit these files!
So, I checked for tests on `make test-unit-non-plugin` and found one failed.
I think this is caused by the docker build error on `cmd/config/internal/commands/e2e/e2econtainerconfig/` dir.

I'm sorry for the inconvenience. Please exec `go mod tidy` on `cmd/config/internal/commands/e2e/e2econtainerconfig/` dir?

**Comment by koba1t** [comment]
/lgtm

Hi @natasha41575 
Could you recheck it and run GitHub actions?

**Pull request merged**
