### PR TITLE
Skip kustomize transformers for paths

### PR DESCRIPTION
**Pull request by jbrette**
This PR attempts to fix: Skip kustomize transformers for paths #896

It leverage the work done in https://github.com/kubernetes-sigs/kustomize/pull/1485

It aims to address the following issue:
Make cluster level kind configurable #617 
Do not add namespace to cluster scoped CRDs #552 
Skipping nameprefix for some resource kind #519 
Adding labels only to metadata.labels #330
Skip adding labels to certain paths #519
Unable to disable commonLabels injection using transformer config: Error: conflicting fieldspecs #817

### CODE REVIEW

**Comment by Liujingfang1** [comment]
@jbrette I don't think we agree on which solution kustomize should go with. This is a very important feature. Let's think about it carefully before putting any implementation for it. Would you like open an [KEP](https://github.com/kubernetes/enhancements/tree/master/keps#kubernetes-enhancement-proposals-keps) for this? List and compare different solutions. Then we can bring it into discussion in a SIG-CLI meeting and have people agree on the best solution.

**Comment by jbrette** [comment]
@Liujingfang1 @richardmarshall @sethp-nr I will open the KEP.

**Comment by jbrette** [comment]
@monopole @Liujingfang1 @richardmarshall @sethp-nr As agreed, here is the corresponding [KEP](https://github.com/kubernetes/enhancements/pull/1232)

**Comment by nlamirault** [comment]
@jbrette why close this PR ?

**Comment by jbrette** [comment]
@nlamirault I can't recollect a single "Feature PR" merged to kustomize even when we took the time to open KEP in kubernetes/sig-cli,  it was addressing multiple projects needs and issues. We had quite a lot of "Bug Fixes PR" merged, but no feature one.

So, like the autovar feature #1217 , the inlining feature #1208 , the diamond import #1316 , the SMP for CRD feature, this feature PR was on course to rot. Hence it did not make any sense trying to keep it small to ease the reviewing. It was causing us internal merge issues with additional improvements and bug fixes  waiting in line behind that PR.

Since our project needs those features, we will unfortunately have to maintain them until something equivalent is officially integrated Kustomize. 

Meanwhile in order to reduce our workload, we squashed all the commits and divided by two the numbers of branches we have to maintain. The code for this particular PR has been merged with actual bug fixes here: [transformers branch](https://github.com/keleustes/kustomize/tree/transformers). We pull all those features together and the [associated additional regressions tests](https://github.com/keleustes/kustomize/tree/airshipctl/examples/issues) in [this branch](https://github.com/keleustes/kustomize/tree/airshipctl).

**Pull request closed without merging**
