### PR TITLE
git submodule need origin

### PR DESCRIPTION
**Pull request by charles-chenzz**
fix: #5131

### CODE REVIEW

**Comment by antoooks** [comment]
Hi @charles-chenzz, I checked out to the branch and tested it out using `go test` with URL provided by the issue creator `https://github.com/etc/etc/etc?ref=deadbeefdeafbeef` it seems to parse the host incorrectly. Seems the parser does not support parsing path with more than 2 level of subpath? please find the details below:

```txt
=== RUN   TestNewRepoSpecFromUrl_Smoke/arbitrary_testing
    repospec_test.go:699: https://github.com/etc/etc
    repospec_test.go:702: 
                Error Trace:    /Volumes/Workstation/Project/kustomize/api/internal/git/repospec_test.go:702
                Error:          Not equal: 
                                expected: "/notCloned"
                                actual  : "/notCloned/etc"
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -/notCloned
                                +/notCloned/etc
                Test:           TestNewRepoSpecFromUrl_Smoke/arbitrary_testing
                Messages:       absPath mismatch
    repospec_test.go:710: 
                Error Trace:    /Volumes/Workstation/Project/kustomize/api/internal/git/repospec_test.go:710
                Error:          Not equal: 
                                expected: &git.RepoSpec{raw:"", Host:"https://gist.github.com/", RepoPath:"bc7947cb727d7f9217e7862d961a1ffd.git", Dir:"", KustRootPath:"", Ref:"", Submodules:false, Timeout:0}
                                actual  : &git.RepoSpec{raw:"", Host:"https://github.com/", RepoPath:"etc/etc", Dir:"", KustRootPath:"etc", Ref:"deadbeefdeafbeef", Submodules:false, Timeout:0}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -2,7 +2,7 @@
                                  raw: (string) "",
                                - Host: (string) (len=24) "https://gist.github.com/",
                                - RepoPath: (string) (len=36) "bc7947cb727d7f9217e7862d961a1ffd.git",
                                + Host: (string) (len=19) "https://github.com/",
                                + RepoPath: (string) (len=7) "etc/etc",
                                  Dir: (filesys.ConfirmedDir) "",
                                - KustRootPath: (string) "",
                                - Ref: (string) "",
                                + KustRootPath: (string) (len=3) "etc",
                                + Ref: (string) (len=16) "deadbeefdeafbeef",
                                  Submodules: (bool) false,
                Test:           TestNewRepoSpecFromUrl_Smoke/arbitrary_testing
```

```go
// api/internal/git/repospec_test.go#683

{
	name:      "arbitrary testing",
	input:     "https://github.com/etc/etc/etc?ref=deadbeefdeafbeef",
	cloneSpec: "https://github.com/etc/etc",
	absPath:   notCloned.String(),
	repoSpec: RepoSpec{
		Host:     "https://gist.github.com/",
		RepoPath: "bc7947cb727d7f9217e7862d961a1ffd.git",
	},
},
```

**Comment by charles-chenzz** [comment]
> My go test file content:

> ```// api/internal/git/repospec_test.go#683
>{
>	name:      "arbitrary testing",
>	input:     "https://github.com/etc/etc/etc?ref=deadbeefdeafbeef",
>	cloneSpec: "https://github.com/etc/etc",
>	absPath:   notCloned.String(),
>	repoSpec: RepoSpec{
>		Host:     "https://gist.github.com/",
>		RepoPath: "bc7947cb727d7f9217e7862d961a1ffd.git",
>	},
>},


this testcase was on the testfile or you create it? I didn't quite get the point here ( might need detail explanation sorry)

**Comment by charles-chenzz** [comment]
https://github.com/kubernetes-sigs/kustomize/blob/fb7ee2f4871d4ef054ecd9d2e1bc9b10cbfde4a9/api/internal/git/repospec_test.go#L153-L155

base on the comments here, I think all testcase about submodules won't work here. so that's why your testcase will fail (don't know if I understand it right here)

**Comment by antoooks** [comment]
> https://github.com/kubernetes-sigs/kustomize/blob/fb7ee2f4871d4ef054ecd9d2e1bc9b10cbfde4a9/api/internal/git/repospec_test.go#L153-L155
> 
> https://github.com/kubernetes-sigs/kustomize/blob/fb7ee2f4871d4ef054ecd9d2e1bc9b10cbfde4a9/api/internal/git/repospec_test.go#L689-L691
> 
> base on the comments here, I think that's why submodules testcase won't work here. (don't know if I understand it right here)
> 
> the regression test is introduce in this #5189

Hm that's unfortunate, since the issue OP also didn't include reproduce steps as well. Other changes seems aligned with the proposed solution. I think it's good to go after you update this README to make it stay relevant.

https://github.com/charles-chenzz/kustomize/blob/4b225f68c57a23bf507fa50d19c4326078cebd21/api/krusty/testdata/remoteload/with-submodule/README.md?plain=1#L8-L10

**Comment by charles-chenzz** [comment]
> I think it's good to go after you update this README to make it stay relevant.

the stay relevant means remove the comment in https://github.com/charles-chenzz/kustomize/blob/4b225f68c57a23bf507fa50d19c4326078cebd21/api/krusty/testdata/remoteload/with-submodule/README.md#L8-L10 ? I'm not quite get the points here. sorry

**Comment by antoooks** [comment]
> > I think it's good to go after you update this README to make it stay relevant.
> 
> the stay relevant means remove the comment in https://github.com/charles-chenzz/kustomize/blob/4b225f68c57a23bf507fa50d19c4326078cebd21/api/krusty/testdata/remoteload/with-submodule/README.md#L8-L10 ? I'm not quite get the points here. sorry

Yup, right, you can update it since #5131 is resolved. 😃

**Comment by charles-chenzz** [comment]
> Yup, right, you can update it since https://github.com/kubernetes-sigs/kustomize/issues/5131 has been  resolved, after this PR is merged

ACK. I will let other reviewers opt-in and see if there's anything need to address, would update it on another commit/PR

**Comment by jzelinskie** [comment]
I work with @jakedt -- who reported this issue.
I confirmed that this branch resolves the issue for us.

Thanks!

**Review by annasong20 — CHANGES_REQUESTED** [review]
@charles-chenzz Looks great! Just a few nits that I think will make the code easier to read for future developers.

/lgtm

**Comment by annasong20** [comment]
@antoooks Regarding your earlier comment,

>it seems to parse the host incorrectly. Seems the parser does not support parsing path with more than 2 level of subpath?
> // api/internal/git/repospec_test.go#683
>
> {
>	name:      "arbitrary testing",
>	input:     "https://github.com/etc/etc/etc?ref=deadbeefdeafbeef",
>	cloneSpec: "https://github.com/etc/etc",
>	absPath:   notCloned.String(),
>	repoSpec: RepoSpec{
>		Host:     "https://gist.github.com/",
>		RepoPath: "bc7947cb727d7f9217e7862d961a1ffd.git",
>	},
> },

The parser does support multi-level sub-paths.

I think the problem lies in the test case. You can also see this in the test output you provided. For example, you provider a `github.com` input, but expect the parsed `RepoSpec` to have host `gist.github.com`. These two domains don't match. As another example, by default the parser takes the first 2 segments after the domain as the path to the repo. That would mean that your 3rd and last `etc` specifies the path to the Kustomization within the repo. Therefore, your `absPath` should include an `etc` and your `RepoSpec.RepoPath` should also be `etc`.

And with regards to

> I did so because I noticed that the log message provided by the issue creator seems off, I'm not sure if that's a typo though.

Sharp eye :) No, the lack of a slash in the original issue description is not Kustomize's doing. I hypothesize that in order to generalize his url, the reporter whited out his own url with `etc` and in the process, deleted an extra `/`

**Comment by annasong20** [comment]
> > I think it's good to go after you update this README to make it stay relevant.
> 
> the stay relevant means remove the comment in https://github.com/charles-chenzz/kustomize/blob/4b225f68c57a23bf507fa50d19c4326078cebd21/api/krusty/testdata/remoteload/with-submodule/README.md#L8-L10 ? I'm not quite get the points here. sorry

I'd prefer we not remove this explanation. It doesn't say that Kustomize still contains the bug, only that the hash is a preventative measure against such a bug. It explains why we include a hash, which a new contributor might wonder in the future. You can clarify the sentence if you'd like, but I'd only delete it if you plan to remove the hash from the testing code, which I think is slightly undesirable because we should be careful when testing locally on developers' machines.

**Comment by charles-chenzz** [comment]
@annasong20 I've addressed the nits, could you revisit when you get a chance?

>@charles-chenzz Sorry for the confusion. I didn't know that Prow automatically adds the approve label on lgtm. I will remove the lgtm until we address the nits.

prow won't automatically add the approve label after lgtm maybe it's bug here..

**Review by annasong20 — APPROVED** [review]
> @annasong20 I've addressed the nits, could you revisit when you get a chance?

Looks great! Thanks, @charles-chenzz!!

> > @charles-chenzz Sorry for the confusion. I didn't know that Prow automatically adds the approve label on lgtm. I will remove the lgtm until we address the nits.
> 
> prow won't automatically add the approve label after lgtm maybe it's bug here..

I just tested again and my `lgtm` didn't automatically add an `approve`. I am thoroughly confused. Would investigate if I had more time.

**Pull request merged**
