### PR TITLE
Updated README to use 'bases' instead of 'resources' in overlays examples

### PR DESCRIPTION
**Pull request by mvbakker**
In kustomize v2 `kustomization.yaml` can only refer to files in the same directory as itself, or in subdirectories. Only `bases` can refer to outside paths.

Please refer to: https://github.com/kubernetes-sigs/kustomize/issues/776

### CODE REVIEW

**Comment by chancez** [comment]
I thought `bases` was deprecated according to https://github.com/kubernetes-sigs/kustomize/blob/master/docs/fields.md#bases:

> The bases field was deprecated in v2.1.0.
> Move entries into the resources field. This allows bases - which are still a central concept - to be ordered relative to other input resources.

**Comment by mvbakker** [comment]
@chancez, thanks for the comment, that makes sense. Still when I run `kubectl kustomize overlays/staging/` it with the `resources` right now it fails and I get the following error:

`Error: rawResources failed to read Resources: Load from path ../../base failed: '../../base' must be a file (got d='/Users/local/path/to/kustomize_helloWorld/base')`

Am I doing something wrong or should I propose a different solution in the PR?

**Comment by khrisrichardson** [comment]
@mvbakker check out https://github.com/kubernetes-sigs/kustomize#kubectl-integration, which explains the version disparity. Clearly identified versioned docs would go a long way. Of course one could always browse the docs from a [specific tag](https://github.com/kubernetes-sigs/kustomize/tree/v2.0.3/docs) in github, but it's not obvious that one ought to do that.

Maybe creating a separate `kubectl-vX.Y.Z` tag would also help ever so slightly, albeit altogether no more obvious without something directing folks there. If only markdown supported drop-down lists, which would obviate the need for creating a large version matrix. And I have no idea where the source for the http://kustomize.io website resides.

**Comment by YiannisGkoufas** [comment]
Sorry to open this again, I am a bit confused.
The behaviour that I noticed. My structure is this:

image

And in my high-level kustomization I have this:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crds
- apps
- rbac
```
When I issue `kustomize build ./deploy-kustomize` it doesn't complain and outputs the generated yaml.
When I issue `kubectl apply -k ./deploy-kustomize` it doesn't like it and complains about:
```
error: rawResources failed to read Resources: Load from path crds failed: 'crds' must be a file (got d='/deploy-kustomize/crds')
```
When I update the main kustomization.yaml to this:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- crds
- apps
- rbac
```
and execute `kubectl apply -k ./deploy-kustomize` it works without a problem, even though `bases` seems to be deprecated.

If there is any help, this is my kubectl version:
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:26:42Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by Shell32-Natsu** [comment]
@YiannisGkoufas kubectl is using a very old version of Kustomize. It's not strange that the behavior is different.

**Comment by YiannisGkoufas** [comment]
ahh thanks @Shell32-Natsu ! is there a way I can test (or check online) the version of kustomize?

**Comment by Shell32-Natsu** [comment]
For standalone kustomize you can use `kustomize version`. Not sure how to get the kustomize version in kubectl.

**Pull request merged**
