### PR TITLE
Refactor exec plugin load to error if plugin isn't executable

### PR DESCRIPTION
**Pull request by chaosteil**
This addresses issue #1236. Changed the order of execution a bit around and made the existing tests pass accordingly.

### CODE REVIEW

**Comment by chaosteil** [comment]
Signed the CLA

**Comment by monopole** [comment]
This looks good, unfortunately i have a large refactor in progress to launch a stable API module.
Please don't rebase yet.  Hoping by end of day today i can ask you to rebase this.
looks good otherwise

**Comment by chaosteil** [comment]
Sounds good, will be on the lookout!

**Comment by monopole** [comment]
OK, i'm done mucking about with the stuff that concerns this PR.
Please rebase, move your changes to 
```
api/plugins/execplugin
api/plugins/loader
```

**Pull request merged**
