### PR TITLE
deprecate fields: patchesStrategicMerge and patchesJson6902

### PR DESCRIPTION
**Pull request by Liujingfang1**

### CODE REVIEW

**Comment by Liujingfang1** [comment]
@monopole  updated `docs/fields.md`. PTAL

**Comment by monopole** [comment]
can you rebase this?  sorry about that!

i'd like to get this in for v4

**Comment by monopole** [comment]
ping me if you're busy and i'll do it.

**Comment by Liujingfang1** [comment]
@monopole Feel free to take this PR.

**Comment by monopole** [comment]
ack, will do

**Pull request closed without merging**
