### PR TITLE
Add tools package, tidy go mods

### PR DESCRIPTION
**Pull request by mcristina422**
This adds a tools file like https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module

And fixes some changes made in https://github.com/kubernetes-sigs/kustomize/pull/2280

### CODE REVIEW

**Comment by mcristina422** [comment]
/assign @mortent


I think https://github.com/kubernetes-sigs/kustomize/pull/2417 might have caught this. @monopole are there plans to re-enable a similar check?

**Comment by monopole** [comment]
we can re-enable checks.

some checks have benefits in one area, but cause troubles in others.  E.g. maintaining different Go lint checks for different Go modules in this repo is IMO more trouble than simply sticking with one standard for linting across the board. Anyone wanting to increase linting for one module can contribute lint improvements to other modules too.  

thanks!
/lgtm

**Comment by mcristina422** [comment]
@monopole Hmmm, it seems that there is an even larger issue in CI. `golangci-lint-kustomize` is never called in the output logs. 


The top level `Makefile` is never being executed, as the `travis/kyaml-pre-commit.sh` script is only running `make all` in the target subdirectories. I think `.` needs to be added as a target

**Pull request merged**
