### PR TITLE
Add YAML anchor/alias expansion.

### LINKED ISSUE #3675: YAML Anchor support
Starting from `kustomize/v4.0.0` - there is no way for us to build manifests that contain yaml anchors. Previously we were able to workaround by setting `--enable_kyaml=false`.

Example:

proximo.yaml

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /__/metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: &app proximo
    uw.systems/mirror: "true"
  name: *app
spec:
  ports:
  - name: ops
    port: 8080
    protocol: TCP
  - name: http
    port: 6868
    protocol: TCP
  selector:
    app: *app
```

kustomization.yaml

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - proximo.yaml
```

Trying to do a build:

```
$ kustomize build .
Error: considering field 'metadata/name' of object
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /__/metrics
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: &app proximo
    uw.systems/mirror: "true"
  name: *app
spec:
  ports:
  - name: ops
    port: 8080
    protocol: TCP
  - name: http
    port: 6868
    protocol: TCP
  selector:
    app: *app
: wrong Node Kind for metadata.name expected: ScalarNode was AliasNode: value: {*app}
```

Thank you.

### PR DESCRIPTION
**Pull request by monopole**
A first attempt to fix #3675

ALLOW_MODULE_SPAN

### CODE REVIEW

**Comment by natasha41575** [comment]
```
unable to retrieve pull request details: GET https://api.github.com/repos/kubernetes-sigs/kustomize/pulls/4114: 403 API rate limit exceeded for 35.202.162.243. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 37m37s]make: *** [Makefile:257: test-multi-module] Error 2
```

I have never seen this error before. Is there a limit to the rate at which we can run the presubmit for a PR?

**Comment by monopole** [comment]
I've never seen it either.  Also wondering why this PR as opposed to say 4125

**Comment by natasha41575** [comment]
a bit late, but lgtm

/lgtm

**Comment by KnVerey** [comment]
@monopole am I missing something or is this new `DeAnchor()` functionality not being called in the Kustomization inflation path? If there's still more work to do to hook this up, we should reopen the issue.

**Pull request merged**
