### PR TITLE
typo: makes verb number agree with subject

### PR DESCRIPTION
**Pull request by dimitropoulos**
Also changed `one` to `someone` to be more English-as-a-Second-Language friendly.  Anther option would be to use `you` instead of `one`.

### CODE REVIEW

**Comment by monopole** [comment]
welcome and please sign the cla (click Details above).

**Comment by dimitropoulos** [comment]
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.

"a new comment"

**Comment by dimitropoulos** [comment]
@monopole not sure what's happened but I believe I have followed the steps and signed the CLA

**Comment by monopole** [comment]
try all this:

* If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
* If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
* If you have done the above and are still having issues with the CLA being reported as unsigned, please email the CNCF helpdesk: [helpdesk@rt.linuxfoundation.org](mailto:helpdesk@rt.linuxfoundation.org)

**Comment by dimitropoulos** [comment]
screenshot_20190219_100615

hopefully this works this time?

**Comment by dimitropoulos** [comment]
@monopole looks like it worked: thanks for your patience.

**Pull request merged**
