### PR TITLE
Add Remote Kubernetes Secrets as Secret Source

### PR DESCRIPTION
**Pull request by shaneutt**
The purpose of this PR is to enable the ability to use secrets already present in some Kubernetes cluster that the `kustomize` user has access to be usable as the source for secrets generated during `kustomize build` within the `secretsGenerator` directive.

This expands the functionality of `secretGenerator` in a way that avoids secrets being written to local disk, and helps in situations where multiple people need to deploy the same environment in a shared manner, by providing a simple option to handle secrets that need to be shared across team members for that environment.

The core functionality itself works, but presently I'm interested in getting some early feedback. I would like to hear general thoughts on this, and see what would be preferred for how tests are implemented for it.

https://github.com/kubernetes-sigs/kustomize/pull/845/commits/3dcdd18f5e1dc4fcd47373e02a1e4e3c4d305fd7 contains the changes made to enable the functionality thus far, and https://github.com/kubernetes-sigs/kustomize/pull/845/commits/ffb18c90afc122f1e657f191779b8632937e6242 contains the vendoring that was done to update `client-go`.

https://github.com/kubernetes-sigs/kustomize/issues/847#issue-416578021 is the relevant feature request.

### CODE REVIEW

**Comment by Liujingfang1** [comment]
This can be covered by the [plugin](https://github.com/kubernetes-sigs/kustomize/pull/760) approach for secretGenerator. 
Once the plugin mechanism is merged, @shaneutt you can create a go-plugin to read secret from cluster.

**Comment by shaneutt** [comment]
Thank you for the update @Liujingfang1, I appreciate it :)

Do you happen to have even a rough estimate of when you expect that might be finished?

**Comment by monopole** [comment]
goplugins coming soon  - working through reviews.

Thanks for the contribution.  

In general, a PR that imports 1000 files isn't going to make it unless there's a supporting KEP describing the whys and alternatives rejected.     Kustomize is now being vendored into kubectl, so vendoring of this size has a ripple effect.

See also https://github.com/kubernetes-sigs/kustomize#feature-requests, which could probably use more prominence.  Trying to avoid having someone do a bunch of work and then get their feature PR closed.

**Comment by shaneutt** [comment]
Thank you @monopole.

> In general, a PR that imports 1000 files isn't going to make it unless there's a supporting KEP describing the whys and alternatives rejected. Kustomize is now being vendored into kubectl, so vendoring of this size has a ripple effect.

Note that the huge number of changes was due to vendoring, and my actual changes were relatively small. I separated my changes from the vendor changes in two different commits, as noted in the description.

> See also https://github.com/kubernetes-sigs/kustomize#feature-requests, which could probably use more prominence. Trying to avoid having someone do a bunch of work and then get their feature PR closed.

:+1: indeed, this was seen and https://github.com/kubernetes-sigs/kustomize/issues/847#issue-416578021 was linked in the description. As far as closing the PR I'm not bothered by it but I appreciate that, I appreciate the feedback and I'll close this in deference to plugins landing in the near future.

Thank you for your time, looking forward to plugins :smiley:

**Comment by monopole** [comment]
So hang on to this - i really like your README.  Well done.  I think goplugin will work fine here, to unblock you and try out the feature.

**Comment by shaneutt** [comment]
Sounds good @monopole :+1: 

I'll hang on to it and watch for plugins to land.

**Pull request closed without merging**
