### PR TITLE
UnPin api

### PR DESCRIPTION
**Pull request by phanimarupaka**
@monopole

### CODE REVIEW

**Comment by pwittrock** [comment]
what is the motivation for this?

**Comment by monopole** [comment]
develop against "head"

**Comment by phanimarupaka** [comment]
Here is the PR describing the motivation

https://github.com/kubernetes-sigs/kustomize/pull/2042/files

**Comment by monopole** [comment]
another osx  download failure - filed #2045 
@pwittrock you use osx - can you take a look please?

**Pull request merged**
