### PR TITLE
Run kustomize tests on OSx

### PR DESCRIPTION
**Pull request by pwittrock**
Originally tried to get windows working, but struggled with it so just doing OSX for now and @kenmaglio will take a swing at Win.

### CODE REVIEW

**Comment by kenmaglio** [comment]
I can easily assist ( and have actually started it already ) to convert the shell script to powershell.
I have the skeleton working, but I am not familiar at all with knowing if the tests / linting are working correctly.

I have all the pre-req's worked out as well.

Not too familiar with CI other than Jenkins atm. But I'm sure I can learn others easily enough.

**Comment by pwittrock** [comment]
@kenmaglio That would be great for you to take over.  I can get linux and mac working well, but don't have the background for windows.  How about I change this just to add Mac support?

**Comment by kenmaglio** [comment]
Sure. I probably need help on my side, because while I can convert and know how windows-ish things work. What CI the group wants to use to start supporting Windows is another.

**Comment by pwittrock** [comment]
@kenmaglio Sounds good.  Lets follow up on #834.

> What CI the group wants to use to start supporting Windows is another.

SG.  If we can get it working on Travis, that would probably be the smallest delta from where we are at.  If that isn't practical we will have to do something else.

**Comment by monopole** [comment]
well, osx looked pretty easy, thanks

Will be interesting to see how well travis supports windows.

**Pull request merged**
