### PR TITLE
fix: typo in example kustomization.yaml in README

### PR DESCRIPTION
**Pull request by paololazzari**
fixes https://github.com/kubernetes-sigs/kustomize/issues/5362

### CODE REVIEW

**Comment by sarab97** [comment]
@paololazzari can you sign the CLA. 
And welcome to kubernetes.
/lgtm

**Review by kundan2707 — COMMENTED** [review]
/lgtm

**Comment by sarab97** [comment]
@paololazzari if you still intend for this PR to go through can you take action on CLA.
Thanks

**Comment by sarab97** [comment]
No update on cla closing for now. 
/close

**Pull request closed without merging**
