### PR TITLE
Validate originalFields when three dashed are used

### LINKED ISSUE #2434: Index out of range setting image
**execution and error:**
```
$ kustomize edit set image controller=gcr.io/myproject/airflow-operator:56fb935

panic: runtime error: index out of range [-1]

goroutine 1 [running]:
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/kustfile.(*kustomizationFile).parseCommentedFields(0xc0000aca40, 0xc00013c000, 0x32b, 0x380, 0x0, 0x0)
        /private/tmp/kustomize-20200117-60956-18qh1a4/kustomize/internal/commands/kustfile/kustomizationfile.go:200 +0x7b9
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/kustfile.(*kustomizationFile).Read(0xc0000aca40, 0x6278b80, 0xc0000aca40, 0x0)
        /private/tmp/kustomize-20200117-60956-18qh1a4/kustomize/internal/commands/kustfile/kustomizationfile.go:158 +0x2b0
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/edit/set.(*setImageOptions).RunSetImage(0xc0005d8088, 0x55ef820, 0x6278b80, 0x1, 0x0)
        /private/tmp/kustomize-20200117-60956-18qh1a4/kustomize/internal/commands/edit/set/setimage.go:119 +0x76
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/edit/set.newCmdSetImage.func1(0xc000028280, 0xc0002330c0, 0x1, 0x1, 0x0, 0x0)
        /private/tmp/kustomize-20200117-60956-18qh1a4/kustomize/internal/commands/edit/set/setimage.go:82 +0xab
github.com/spf13/cobra.(*Command).execute(0xc000028280, 0xc000233090, 0x1, 0x1, 0xc000028280, 0xc000233090)
        /private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000140f00, 0x9, 0x55d2100, 0xc000390fa0)
        /private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /private/tmp/kustomize-20200117-60956-18qh1a4/.brew_home/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /private/tmp/kustomize-20200117-60956-18qh1a4/kustomize/main.go:23 +0x71

```
**Cause**
three dashes (---) after a commented header on `kustomization.yaml`

`kustomize version`
```
{Version:3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-17T14:28:58+00:00 GoOs:darwin GoArch:amd64}
```
`kustomization.yaml`
```yaml
# Licensed to the Apache Software Foundation (ASF) under one or more
# ...
# ...
# limitations under the License.

---
resources:
- manager.yaml
```
`manager.yaml`
```yaml
# Licensed to the Apache Software Foundation (ASF) under one or more
# ...
# ...
# limitations under the License.

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - command:
            - /manager
          args:
            - --enable-leader-election
          image: controller:latest
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10

```
**Expected result:**
```yaml
# Licensed to the Apache Software Foundation (ASF) under one or more
# ...
# ...
# limitations under the License.

---
resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: gcr.io/myproject/airflow-operator
  newTag: 56fb935
```

/kind bug

### PR DESCRIPTION
**Pull request by msgongora**
Fix #2434

### CODE REVIEW

**Comment by pwittrock** [comment]
would you add a test?

**Comment by msgongora** [comment]
I tried to write test as recommended on **bugs.md** but I got lost since I'm still not fluent in golang. Would you mind to point me in the right direction? What would be a right test from here: **/api/krusty** to base mine.

**Comment by monopole** [comment]
Once #2505 goes in, try adding a test for this change to 
```
api/internal/target/kusttarget_test.go TestLoad
```

**Comment by monopole** [comment]
thankyou for reading [bugs](https://github.com/kubernetes-sigs/kustomize/blob/master/docs/bugs.md).  That doc is targeted to bugs in `kustomize build` (transforming yaml),  and has worked out well for concisely describing build problems.

This bug surfaces in the `edit` command.

Not having dug too deep, this bug appears related to both the fact that a kustomization file shouldn't have  `---` in it (see comment in  #2434), and attempts to preserve comments in the kustomization YAML through the edit process.

@pwittrock is right that writing a test that fails without your change, and passes with your change would be for the best

**Comment by monopole** [comment]
/ok-to-test

BTW locally just enter `make` to run all tests.

**Comment by monopole** [comment]
Still waiting for a test in this PR

**Comment by monopole** [comment]
pls reopen if a test is supplied

**Pull request closed without merging**
