### PR TITLE
helm values on inflator config

### PR DESCRIPTION
**Pull request by epcim**
Proposal. Let me know whether welcome and suggest updates.

- It solve issue with relative path to values + allows some merge capabilities for values.yaml
- Would be nice to rename to: Values (map[string]interface{} and today Values -> ValuesFile string as a path, but such change now would not be backward compatible.

### CODE REVIEW

**Comment by Shell32-Natsu** [comment]
/lgtm

Thanks!

**Comment by Shell32-Natsu** [comment]
Please split your commit so it won't cross modules

**Comment by Shell32-Natsu** [comment]
Please add or expand the test as well. Also please update the documentation https://github.com/kubernetes-sigs/cli-experimental/blob/master/site/content/en/guides/extending_kustomize/builtins.md

**Comment by monopole** [comment]
I'm sorry, this was merged by mistake, and i reverted it.  Please address @Shell32-Natsu comments - tests and doc  thanks.

**Pull request merged**
