### PR TITLE
Update go.mod to go 1.14

### PR DESCRIPTION
**Pull request by pankona**
Refs: #2566 

## Updates

- update all `go.mod` to go 1.14 in the following way.

confirm current go version written in go.mod in this repository

```sh
$ for i in $(find . -name go.mod); do grep ^go $i; done | sort | uniq
go 1.12
go 1.13
go 1.14
```

As a result, it seems `go 1.12 and go 1.13` exist in this repository.
I've run the following script to update them to `go 1.14`.

```sh
for i in $(find . -name go.mod); do
    sed -i -e 's/go 1.12/go 1.14/' $i
    sed -i -e 's/go 1.13/go 1.14/' $i
done
```

Then confirm again
```sh
$ for i in $(find . -name go.mod); do grep ^go $i; done | sort | uniq
go 1.14
```

- I've run `travis/check-go-mod.sh` to do `go tidy` for all `go.mod/sum`
- I've run `make all` to confirm build and test

### CODE REVIEW

**Comment by pankona** [comment]
Hi, I've signed the CLA. Please take a look!

image

**Comment by pankona** [comment]
Please review my pull request. Thanks in advance! 😋 

/assign @pwittrock

**Comment by monopole** [comment]
/lgtm
/approve
welcome to k8s @pankona 

fixes #2566

**Pull request merged**
