### PR TITLE
Add maintainer

### PR DESCRIPTION
**Pull request by phanimarupaka**
@monopole @Liujingfang1

### CODE REVIEW

**Comment by monopole** [comment]
/ok-to-test

(fwiw)

**Comment by Liujingfang1** [comment]
It looks like kubernetes-sigs is a different org now. https://github.com/kubernetes/community/blob/master/community-membership.md#kubernetes-ecosystem

**Comment by monopole** [comment]
yeah that's being pursued in some other pr now, thanks

**Pull request merged**
