### PR TITLE
Add --log-steps flag

### PR DESCRIPTION
**Pull request by ZhuGongpu**
Prerequisite of GoogleContainerTools/kpt#995.

### CODE REVIEW

**Comment by Liujingfang1** [comment]
@mortent @Shell32-Natsu  Does the flag `--log-steps` look good to you?

**Comment by Shell32-Natsu** [comment]
@frankfarzan what do you think?

**Comment by frankfarzan** [comment]
@ZhuGongpu could you provide an example output to the tracking issue.

We should also discuss whether this should be on by default.

**Comment by ZhuGongpu** [comment]
@frankfarzan  Take [function-export-blueprint](https://github.com/GoogleContainerTools/kpt/tree/master/package-examples/function-export-blueprint) for example,

```sh
kpt pkg get https://github.com/GoogleContainerTools/kpt/package-examples/function-export-blueprint function-export-blueprint
cd function-export-blueprint
```

Then run `kustomize fn run . --log-steps` will output something like this into **`stderr`**:

```
Running gcr.io/kpt-functions/label-namespace
Running gcr.io/kpt-functions/gatekeeper-validate
```

For newly added features, like `kpt fn export`, we should definitely turn on the `--log-steps` flag by default. For existing ones, I would prefer no changes to avoid any unexpected confusion.

**Comment by frankfarzan** [comment]
How about failure cases? We want to probably to include a) Function b) Exit code.

**Comment by ZhuGongpu** [comment]
> How about failure cases? We want to probably to include a) Function b) Exit code.

@frankfarzan  Here is an example out by removing `owner` from the example blueprint:

```
Running gcr.io/kpt-functions/label-namespace
Running gcr.io/kpt-functions/gatekeeper-validate
Error: Found 1 violations:

[1] Deployment objects should have an 'owner' label indicating who created them.

name: "nginx-deployment"
path: resources/resources.yaml


error: exit status 1
```

The output clearly shows which function has been run before the error happened. In this case, `gatekeeper-validate` failed.

**Comment by Liujingfang1** [comment]
/lgtm
/approve

Thanks for adding this @ZhuGongpu.

**Pull request merged**
