### PR TITLE
replace genargs with two separate annotations

### PR DESCRIPTION
**Pull request by natasha41575**
no more `genArgs`

follow up to https://github.com/kubernetes-sigs/kustomize/pull/4061#discussion_r675725163

### CODE REVIEW

**Review by monopole — COMMENTED** [review]
/lgtm

less code is best code.  nicely done.

**Comment by natasha41575** [comment]
@monopole Sorry - I rebased, so this needs another LGTM

**Comment by natasha41575** [comment]
@monopole @KnVerey PTAL

**Pull request merged**
