### PR TITLE
Adds documentation for choco package for windows

### PR DESCRIPTION
**Pull request by kenmaglio**
Adds documentation for the chocolatey package now available for kustomize.

### CODE REVIEW

**Comment by kenmaglio** [comment]
I signed it

**Comment by Liujingfang1** [comment]
@kenmaglio I don't have a windows computer now. Let me verify it later.

**Comment by kenmaglio** [comment]
@Liujingfang1 I just saw 2.0.2 dropped. Let me actually get that built and updated so you can test that. I'll let you know when it's updated.

**Comment by kenmaglio** [comment]
It's not approved yet, might take a day or two on moderators.
I'll update again once it's public and listed on chocolatey's package store.

But the command to test the new version: 
choco install kustomize --version 2.0.2
choco uninstall kustomize --version 2.0.2

**Comment by kenmaglio** [comment]
choco_kustomize

**Comment by monopole** [comment]
err - we have no tests that qualify a release on Windows, so i'm hesitant to do this.

Do you have any suggestions to fix this?

**Comment by kenmaglio** [comment]
So I guess I'm confused on what you're asking @monopole. You have tests in this package, which tests the go code ( your unit tests which I see ).  

Are you asking how to test the released windows executable your project already builds, and users on windows already using?

Since chocolatey is an equivalency for package management in windows, are you asking how to test that the package is written correctly, etc.   ?

Chocolatey has a pretty decent CI / CD around new packages ( and updates ) and every package is moderated, inspected, tested, etc.   Can't put something up on chocolatey package store publically without that.

The latest release 2.0.2 of the package just went through verification.
You can see here: https://gist.github.com/choco-bot/62573e21d8bd3fbdcf3f63a6a6859d93

Could you explain more what exactly you are are looking for when you mention 'tests that qualify a release on Windows' ?

**Comment by monopole** [comment]
Any commit - thus all releases - must execute
https://github.com/kubernetes-sigs/kustomize/blob/master/bin/pre-commit.sh
without error.  We only run this on linux.

**Comment by monopole** [comment]
We do cross-compile for windows, and create a release - but it's not qualified beyond compilation.

**Comment by kenmaglio** [comment]
If you do not qualify it then why do you release it when you release the Linux version. Packaging it doesn't affect the release, nor testing of the code. 

It sounds like you're asking me to translate your test runner into powershell that could be run on a Windows machine that uses go, that you could run your tests on Windows as well, before you compile for Windows going forward?

this has zero applicability of how your executable is put on a machine. if you're only ever going to run and test and support things that run on Linux, then stop cross compiling.

Windows users are going to use this regardless if you run a test in Linux or not. If you're building it it'll get used. 

Providing an easier way to simply download and put it on a Windows machine has again no impact on the decision to test the code on windows before compilation.

**Comment by kenmaglio** [comment]
And I thought that was the whole purpose of go was that it was one code, one set of tests, which once compiled works identically cross platform.

**Comment by kenmaglio** [comment]
And you do realize what chocolatey is doing right? it's simply downloading the executable from GitHub directly that you all produce would you release. It's then simply sticking that in a place that Windows understands at a command line. It's doing one fancy thing that chocolatey he knows how to do.. which is point the command ... 'kustomize' ... To the actual executable that was downloaded from GitHub. there is zero modification of the executeable you provide.  It is only the method of how to get it to the machine that chocolatey provides that is different than someone manually downloading the executable themselves from your release page.

**Comment by kenmaglio** [comment]
Chocolatey package approved.

https://chocolatey.org/packages/kustomize

**Comment by monopole** [comment]
> If you do not qualify it then why do you release it?
> if you're only ever going to run and test and support things that run on Linux, then stop cross compiling.

Right, hence: https://github.com/kubernetes-sigs/kustomize/issues/791

We compile for Windows, but don't execute tests there, so its disingenuous to release a Windows build.

It would be great to have a Windows user build out a release process for windows, so that a Windows release would have some testing.

**Comment by kenmaglio** [comment]
As mentioned in [Remove the windows OS release #791](https://github.com/kubernetes-sigs/kustomize/issues/791). This is not up to you @monopole .

Will look forward to discussions in the forums. But since windows isn't getting pulled anytime soon or untill that time happens....  

@Liujingfang1 Let me know if you have questions testing.  

Thanks

**Comment by pwittrock** [comment]
We should make it clear to readers of this document who the maintainers of the managers (either brew (am I correct?) or choco installations) are and where they should file issues instead.

Would you update the change with a message about how to get support e.g. go to https://chocolatey.org/packages/kustomize?

Is there automation that is triggered automatically, or will you be manually updating it for each release?  What is the plan for maintaining this going forward?

**Comment by kenmaglio** [comment]
I can definitely update the documentation here to go to that page. 

Right now it's a manual re-package  ( but it's a very small amount of effort currently ). I've turned on notifications on the release page for myself, so I can be notified. 

There are automation applications available which I want to look at ( also because we use Choco and do this type of thing at work ). Those automations look at the releases page for and if there was a new release pull that executable file down automatically, calculate checksums, re-package, and submit for approval through Chocolatey.com.

**Pull request merged**
