### PR TITLE
Accumulate resources in parallel

### PR DESCRIPTION
**Pull request by flo-02-mu**
As suggested in https://github.com/kubernetes-sigs/kustomize/issues/2950 it would be nice to load base resources in parallel. With this PR an additional parameter is introduced:
`kustomize build --max_parallel_accumulate n` accumulates the resources in parallel go routines.
The default value equals to 1, so that the existing behaviour remains.

### CODE REVIEW

**Comment by Shell32-Natsu** [comment]
@monopole What do you think about this?

**Comment by Shell32-Natsu** [comment]
@flo-02-mu Regardless of whether this proposal will be accepted, please add some tests to cover these new behaviors.

**Comment by flo-02-mu** [comment]
> @flo-02-mu Regardless of whether this proposal will be accepted, please add some tests to cover these new behaviors.

In https://github.com/kubernetes-sigs/kustomize/pull/3172/files#diff-840240dda964a03a3ad4437883ccbfbc0b84099f695a083bc7642b7c14df46c6R263 I reused the existing tests but with 16 parallel accumulators. Do you have any specific tests in mind?

**Comment by Shell32-Natsu** [comment]
@flo-02-mu In that test you only check is there an error, and there is only one test case. Probably we should also check the result. I understand that the order may be different in each run, but that is also possible to check. Also you may want to add some utilities to `testutils` for parallel testing.

**Comment by flo-02-mu** [comment]
It does not only test for errors. It checks for the content as well: https://github.com/kubernetes-sigs/kustomize/pull/3172/files#diff-840240dda964a03a3ad4437883ccbfbc0b84099f695a083bc7642b7c14df46c6R273

**Comment by Shell32-Natsu** [comment]
Sorry. My fault. But I still want to have more test coverage.

Also waiting for input from @monopole

**Comment by flo-02-mu** [comment]
@Shell32-Natsu Some existing tests are now duplicated with parallel execution and a dedicated one is added, too.

**Comment by monopole** [comment]
Before adding this complexity, we all need to see some benchmark tests
https://dave.cheney.net/2013/06/30/how-to-write-benchmarks-in-go
I can think of other ways to improve concurrency, but w/o benchmarks we don't know
that we're solving a problem or just making things more complex.
Would you be willing to add some benchmark test first?

**Comment by flo-02-mu** [comment]
> Would you be willing to add some benchmark test first?

I gave it a try and added a benchmark test: https://github.com/kubernetes-sigs/kustomize/pull/3172/files#diff-840240dda964a03a3ad4437883ccbfbc0b84099f695a083bc7642b7c14df46c6R407
My main intention was to speed up git checkouts, that's why the test uses git endpoints. Benchmark tests are currently not included in the Makefile (and probably it is not a good idea?), so here my local output for the test:
```
$ go test -bench=.
goos: darwin
goarch: amd64
pkg: sigs.k8s.io/kustomize/api/internal/target
BenchmarkMaxParallelAccumulate1-8              1        43338623097 ns/op
BenchmarkMaxParallelAccumulate2-8              1        31191153303 ns/op
BenchmarkMaxParallelAccumulate3-8              1        25994556832 ns/op
PASS
ok      sigs.k8s.io/kustomize/api/internal/target       101.583s
```

**Comment by Shell32-Natsu** [comment]
Please rebase.

It will be good if you can create a distinct PR with a benchmark script so that we can have a base line to measure the performance benefits. It can be a simple script under `hack` directory.

**Comment by flo-02-mu** [comment]
@Shell32-Natsu I added a script, but there is not much added value since it just executes go test. An additional test run now does the baseline benchmark without the parallel option set.

**Pull request closed without merging**
