### PR TITLE
update gopkg.in/yaml.v2 to v2.3.0, yaml.v3 to latest

### PR DESCRIPTION
**Pull request by laverya**
this fixes issue #947

https://github.com/go-yaml/yaml/compare/v2.2.8...v2.3.0 only contains the single relevant commit.

### CODE REVIEW

**Comment by laverya** [comment]
...evidently v3 changed indentation behavior: https://github.com/go-yaml/yaml/compare/4206685974f2...v3

**Comment by laverya** [comment]
...this is probably going to be bigger than I thought it was

**Comment by pwittrock** [comment]
@laverya can you confirm if this is a still an issue with the latest customize release?

**Comment by laverya** [comment]
I'll check!

**Comment by laverya** [comment]
Just checked, and 3.6.1 still exhibits this behavior @pwittrock:

`kustomization.yaml`
```yaml
resources:
- deployment.yaml
```

`deployment.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      component: test
  template:
    metadata:
      labels:
        component: test
    spec:
      containers:
        - name: test
          image: "test"
          env:
            - name: DATABASE_URL
              value: postgres://{{repl ConfigOption "database_user"}}:{{repl ConfigOption "database_password"}}@db.{{repl Namespace}}.svc.cluster.local:5432/db
```

yields this:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      component: test
  template:
    metadata:
      labels:
        component: test
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgres://{{repl ConfigOption "database_user"}}:{{repl ConfigOption
            "database_password"}}@db.{{repl Namespace}}.svc.cluster.local:5432/db
        image: test
        name: test
```

**Comment by monopole** [comment]
Closing this as out of date, but reopened #947.  
If you have the bandwidth, please send a PR for a unit test that shows the behavior.
https://kubernetes-sigs.github.io/kustomize/contributing/bugs

**Pull request closed without merging**
