### PR TITLE
Windows Tests - Precommit Script

### PR DESCRIPTION
**Pull request by kenmaglio**
Done:
- Invoke-PreCommit.ps1 added to bin
- Documentation added

Working:
- How do we automate this in Travis if possible like the Linux side does today?

Results:
- Linting passes
- Tests do not pass
- Mdrip passes

### CODE REVIEW

**Comment by kenmaglio** [comment]
Currently mdrip has an issue ( race condition? )

```
============== begin Test-Examples
F0305 11:25:19.498657   23076 util.go:41] delete temp file: remove C:\Users\magliok\AppData\Local\Temp\mdrip-file-128995271: 
The process cannot access the file because it is being used by another process.
goroutine 1 [running]:
github.com/monopole/mdrip/vendor/github.com/golang/glog.stacks(0xc000299d00, 0xc000245860, 0xcd, 0xe4)
        C:/_go/src/github.com/monopole/mdrip/vendor/github.com/golang/glog/glog.go:769 +0xdb
github.com/monopole/mdrip/vendor/github.com/golang/glog.(*loggingT).output(0xbe8540, 0xc000000003, 0xc000106580, 0xba5633, 0x7, 0x29, 0x0)
        C:/_go/src/github.com/monopole/mdrip/vendor/github.com/golang/glog/glog.go:720 +0x324
github.com/monopole/mdrip/vendor/github.com/golang/glog.(*loggingT).printDepth(0xbe8540, 0xc000000003, 0x1, 0xc0000e7cd8, 0x1, 0x1)
        C:/_go/src/github.com/monopole/mdrip/vendor/github.com/golang/glog/glog.go:646 +0x130
github.com/monopole/mdrip/vendor/github.com/golang/glog.(*loggingT).print(0xbe8540, 0x3, 0xc0000e7cd8, 0x1, 0x1)
        C:/_go/src/github.com/monopole/mdrip/vendor/github.com/golang/glog/glog.go:637 +0x61
github.com/monopole/mdrip/vendor/github.com/golang/glog.Fatal(0xc0000e7cd8, 0x1, 0x1)
        C:/_go/src/github.com/monopole/mdrip/vendor/github.com/golang/glog/glog.go:1128 +0x5a
github.com/monopole/mdrip/util.Check(0x88e6ed, 0x10, 0x905760, 0xc000304060)
        C:/_go/src/github.com/monopole/mdrip/util/util.go:41 +0xa8
github.com/monopole/mdrip/subshell.(*Subshell).Run.func1(0xc000092760)
        C:/_go/src/github.com/monopole/mdrip/subshell/subshell.go:229 +0x63
github.com/monopole/mdrip/subshell.(*Subshell).Run(0xc0000e7e90, 0xc000358000)
        C:/_go/src/github.com/monopole/mdrip/subshell/subshell.go:281 +0x43d
main.trueMain(0xc0000653e0, 0x0, 0x0)
        C:/_go/src/github.com/monopole/mdrip/main.go:42 +0x46f
main.main()
        C:/_go/src/github.com/monopole/mdrip/main.go:70 +0x5b
============== end Test-Examples : FAILURE code=False
```

**Comment by pwittrock** [comment]
Hm.  @kenmaglio feel free to disable tests if only a subset are failing.  We can move incrementally toward 100%.

@monopole is this testing that the tutorials are up to date and work?

**Comment by monopole** [comment]
Yes.  It's the only thing i care about w/r to testing on a different op-sys.

Looks like an abrupt failure right at the start - not necessarily test-specific.  I'd need windows to investigate further.

**Comment by monopole** [comment]
@kenmaglio  Thanks for your efforts here.

Over wknd fired up mdrip+bash on a windows box. 

Found some issues, including the failures you mentioned.  Now that I've dug into it a bit, I feel they are rooted not in kustomize but in how both mdrip and the examples themselves depend on bash and the interface between Go and subprocesses.  Bash is the default shell on OSX, and most linux distros, and the examples (with mdrip as a driver) work fine on those systems.  Bash can be launched from within Powershell, but the whole - mdrip + example running in bash subprocesses don't work the same way on Windows and need more investigation. 

So, to close #834 i'd be fine with a travis precommit that, _for windows only, omitted the mdrip based tests_ and only ran the Go unit tests.  The unit tests in the target package are very high level, and I now know they work on Windows, so i'm OK with just that for now.

**Comment by monopole** [comment]
ping - are you happy with the powershell script as is?

**Comment by kenmaglio** [comment]
I am happy with this powershell script now ( removed the mdrip testing ).
Sorry I haven't posted in a while, life got crazy for a bit. 

I don't have experience with Travis to build in the windows support to actually call this script. 
But if someone else wants to take a stab at that in another commit.
This script should work.

**Comment by kenmaglio** [comment]
This is my thoughts on a travis file modification - but didn't want to hold this script up.

https://gist.github.com/kenmaglio/1c5e3f9c888ac3806690c70294694e16

**Pull request merged**
