### PR TITLE
improve test code coverage in transformers

### PR DESCRIPTION
**Pull request by beautytiger**
`interface{}` will match anything, so `nil` is not needed.

### CODE REVIEW

**Comment by monopole** [comment]
@beautytiger would you be willing to convert this PR into a test that demonstrates the point being made by @richardmarshall ?
I.e. a test that this PR would have caused to fail

**Comment by beautytiger** [comment]
@richardmarshall 
Great lesson, thanks for your guide.
@monopole
I have changed this pr to target imporve test coverage.
How about the changes.
pls review.

**Comment by monopole** [comment]
/lgtm
/appprove
thanks!

**Pull request merged**
