### PR TITLE
Improve `localizer` readability

### PR DESCRIPTION
**Pull request by annasong20**
This PR aims to improve the readability of code under `api/internal/localizer`. Specifically, it addresses readability-related code review feedback from #4797.

### CODE REVIEW

**Comment by yuwenma** [comment]
I think we want to find a better name to replace `Args` and `raw`...
- `args` is normally used on string slice variables which is used as CLI argument.
e.g. `kustomize build <ARGS>` see [code ](https://github.com/kubernetes-sigs/kustomize/blob/master/kustomize/commands/build/build.go#L73)
- `raw` should be either 1. more specific 2. more concise (e.g. `rawScope` -> `scope`), defer to whether the variables are used in the main logic (meaning matters) or in a helper methods (concise wins). Shall we change `establishScope` to something like  `GetEffectiveScope` or `EffectiveScope` like `[effectiveNamespace](https://github.com/kubernetes-sigs/kustomize/blob/fcfd30ca18bf5d533e1c1b6e94bb47ffd2c24f18/kyaml/resid/resid.go#L149)` 
	So the code will be 
```
// Before
scope, err := establishScope(rawScope, rawTarget, ldr, fSys)
// After
effectiveScope, err := GetEffectiveScope(scope, target, ldr, fSys)
```

**Comment by annasong20** [comment]
> I think we want to find a better name to replace `Args` and `raw`...
> 
> * `args` is normally used on string slice variables which is used as CLI argument.
>   e.g. `kustomize build <ARGS>` see [code ](https://github.com/kubernetes-sigs/kustomize/blob/master/kustomize/commands/build/build.go#L73)
> * `raw` should be either 1. more specific 2. more concise (e.g. `rawScope` -> `scope`), defer to whether the variables are used in the main logic (meaning matters) or in a helper methods (concise wins). Shall we change `establishScope` to something like  `GetEffectiveScope` or `EffectiveScope` like `[effectiveNamespace](https://github.com/kubernetes-sigs/kustomize/blob/fcfd30ca18bf5d533e1c1b6e94bb47ffd2c24f18/kyaml/resid/resid.go#L149)`
>   So the code will be
> 
> ```
> // Before
> scope, err := establishScope(rawScope, rawTarget, ldr, fSys)
> // After
> effectiveScope, err := GetEffectiveScope(scope, target, ldr, fSys)
> ```

1. Sure! I can change `raw` as you've dictated here.
2. Yeah, I wanted `Args` to represent the cleaned, validated CLI arguments for localize. Unfortunately, it's not a `[]string`. I've been thinking about alternatives. How do you like `Spec` or `Constants`?

**Comment by yuwenma** [comment]
> > I think we want to find a better name to replace `Args` and `raw`...
> > 
> > * `args` is normally used on string slice variables which is used as CLI argument.
> >   e.g. `kustomize build <ARGS>` see [code ](https://github.com/kubernetes-sigs/kustomize/blob/master/kustomize/commands/build/build.go?rgh-link-date=2022-11-15T19%3A30%3A54Z#L73)
> > * `raw` should be either 1. more specific 2. more concise (e.g. `rawScope` -> `scope`), defer to whether the variables are used in the main logic (meaning matters) or in a helper methods (concise wins). Shall we change `establishScope` to something like  `GetEffectiveScope` or `EffectiveScope` like `[effectiveNamespace](https://github.com/kubernetes-sigs/kustomize/blob/fcfd30ca18bf5d533e1c1b6e94bb47ffd2c24f18/kyaml/resid/resid.go#L149)`
> >   So the code will be
> > 
> > ```
> > // Before
> > scope, err := establishScope(rawScope, rawTarget, ldr, fSys)
> > // After
> > effectiveScope, err := GetEffectiveScope(scope, target, ldr, fSys)
> > ```
> 
> 1. Sure! I can change `raw` as you've dictated here.
> 2. Yeah, I wanted `Args` to represent the cleaned, validated CLI arguments for localize. Unfortunately, it's not a `[]string`. I've been thinking about alternatives. How do you like `Spec` or `Constants`?

ah, I see. `Args` makes sense.

**Pull request merged**
