### PR TITLE
fix kyaml issue with multiline scalars

### LINKED ISSUE #4066: Kyaml converts multiline scalars to single lines
A round trip in kyaml converts the following:

```
apiVersion: custom
kind: Custom
metadata:
  name: my-resource
spec:
  validation:
    openAPIV3Schema:
      description: CanonicalService is the Schema for the canonicalservices API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
```

into 

```
apiVersion: custom
kind: Custom
metadata:
  name: my-resource
spec:
  validation:
    openAPIV3Schema:
      description: CanonicalService is the Schema for the canonicalservices API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
```

This resource is a snippet taken from [here](https://github.com/GoogleCloudPlatform/anthos-service-mesh-packages/blob/master/asm/canonical-service/controller.yaml#L31). The line breaks in the description fields are lost. 

If this is an issue with go-yaml, we should make the fix in our fork and also file an issue/PR to go-yaml upstream.

### PR DESCRIPTION
**Pull request by natasha41575**
This PR has a fix #4066 in the internal go-yaml fork.

### CODE REVIEW

**Comment by phanimarupaka** [comment]
@KnVerey FYI.

**Comment by KnVerey** [comment]
I see this version of the fix is missing a test added in the upstream PR. After #4071 merges, you'll be able to easily add a reference to an additional upstream PR and pull it in with the script. The script always recreates the fork from scratch, so there will be unnecessary commits that could be rebased out if we care, but using it will guarantee that our internal copy exactly matches what we're trying to get merged.

**Comment by phanimarupaka** [comment]
@natasha41575 @KnVerey If this behavior is intentional and is not a bug, should we revert this change?

**Comment by KnVerey** [comment]
Yes, I agree we should revert it (as well as the commit I made to bring the internal fork in line with the PR) and avoid making changes to the internal fork unless they are critical (e.g. significant regressions). 

Other yaml implementations aren't inherently correct either, but after digging into the spec I think the original behavior was correct. Check out this section in particular: https://yaml.org/spec/1.2/spec.html#id2787109

Specifically: "In a multi-line double-quoted scalar, line breaks are are subject to flow line folding, which discards any trailing white space characters." and example 7.5

**Pull request merged**
