### PR TITLE
cmd/config: support for stdin/stdout in source/sink

### PR DESCRIPTION
**Pull request by pwittrock**

### CODE REVIEW

**Comment by phanimarupaka** [comment]
/lgtm

But standalone test on Intellij is failing for new tests

**Comment by frankfarzan** [comment]
Can you document this behavior? Also, does `sink` now output to stdout?

**Comment by pwittrock** [comment]
Documentation updated.

**Comment by pwittrock** [comment]
> But standalone test on Intellij is failing for new tests

Fixed this by explicitly setting the command arguments to empty

**Pull request merged**
