### PR TITLE
Replace gopkg.in/yaml.v2 with sigs.k8s.io/yaml/goyaml.v2

### PR DESCRIPTION
**Pull request by prashantrewar**
Fixes https://github.com/kubernetes-sigs/kustomize/issues/5419

### CODE REVIEW

**Review by stormqueen1990 — COMMENTED** [review]
These changes look good to me, but I think this needs a `go work sync`. I see an extra change when doing so locally after applying the changes from this PR.

**Comment by prashantrewar** [comment]
Thanks @stormqueen1990, I have made the changes.

**Comment by prashantrewar** [comment]
Thanks @stormqueen1990, I have made the changes.

**Review by stormqueen1990 — COMMENTED** [review]
/lgtm

**Review by natasha41575 — APPROVED** [review]
/lgtm

Thanks for the contribution! Please feel free to check out the [kustomize project boards](https://github.com/orgs/kubernetes-sigs/projects?query=is%3Aopen+kustomize) if you are interested in contributing to more open issues.

**Pull request merged**
