### PR TITLE
Feature: Automatic Creation of 'vars:' and 'varReferences:' sections

### PR DESCRIPTION
**Pull request by jbrette**
The description of the goal for this PR is available at: [issue](https://github.com/kubernetes-sigs/kustomize/issues/1216)

The main idea is to scan the [ResMap](https://github.com/keleustes/kustomize/blob/autov/pkg/transformers/config/resmapscanner.go#L185)
in order to create the [var](https://github.com/keleustes/kustomize/blob/autov/pkg/transformers/config/resmapscanner.go#L208)and [varreference](https://github.com/keleustes/kustomize/blob/autov/pkg/transformers/config/resmapscanner.go#L207)

Those var and varrefence get then merge into the accumulator as if a user had written those my hand in the kustomization.yaml and kustomizeconfig.yaml: [merge](https://github.com/keleustes/kustomize/blob/autov/pkg/accumulator/resaccumulator.go#L91)

### CODE REVIEW

**Comment by jbrette** [comment]
@monopole Latest series of forced push where simply to validate everything was still working ok.

**Comment by jonathanunderwood** [comment]
This looks really helpful.

**Comment by tkellen** [comment]
@Liujingfang1 Is there any chance we might see a review of this in the near future? As ever, thanks sincerely for all your work on kustomize--it has massively reduced the complexity of config management for my project.

**Comment by tkellen** [comment]
@Liujingfang1 Is there any chance we might see a review of this in the near future? As ever, thanks sincerely for all your work on kustomize--it has massively reduced the complexity of config management for my project.

**Comment by jbrette** [comment]
@monopole @Liujingfang1 Can you have a serious at this PR now that it soaked for a while. We do rebase the code a regular interval.

The issue https://github.com/kubernetes-sigs/kustomize/issues/1540 is one of the multiple examples demonstrating that the VarReference will never be up to date.
- A variable can be used anywhere and the default config only contains a handful of fields. It has been build at a time where only string could be used in very limited cases.
- The number of CRDs is increasing, hence that user have to adjust those fields all the time [see](https://github.com/kubeflow/manifests/blob/master/istio/istio/base/params.yaml)

Here is a set of issues where this PR has been useful. Note that we run 'mdrip' on those README.md daily

[./issue_1113/README.md](https://github.com/keleustes/kustomize/blob/allinone/examples/issues/./issue_1113/README.md)
[./issue_1268/README.md](https://github.com/keleustes/kustomize/blob/allinone/examples/issues/./issue_1268/README.md)
[./issue_1251_f/README.md](https://github.com/keleustes/kustomize/blob/allinone/examples/issues/./issue_1251_f/README.md)
[./issue_1540_b/README.md](https://github.com/keleustes/kustomize/blob/allinone/examples/issues/./issue_1540_b/README.md)
[./issue_1540/README.md](https://github.com/keleustes/kustomize/blob/allinone/examples/issues/./issue_1540/README.md)
[./issue_0964/README.md](https://github.com/keleustes/kustomize/blob/allinone/examples/issues/./issue_0964/README.md)
[./issue_0952/README.md](https://github.com/keleustes/kustomize/blob/allinone/examples/issues/./issue_0952/README.md)
[./issue_0680/README.md](https://github.com/keleustes/kustomize/blob/allinone/examples/issues/./issue_0680/README.md)

/cc @ian-howell

**Comment by jbrette** [comment]
This also fixes #0850 as demonstrated [here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues/issue_0850)

**Comment by tkellen** [comment]
@jbrette Out of curiosity, is there a reason you've not expanded this feature to support namespaces?

**Comment by jbrette** [comment]
> @jbrette Out of curiosity, is there a reason you've not expanded this feature to support namespaces?

Can you give us an example. The autovar feature works across namespaces.

**Comment by tkellen** [comment]
> > @jbrette Out of curiosity, is there a reason you've not expanded this feature to support namespaces?
> 
> Can you give us an example. The autovar feature works across namespaces.

Yes of course! We spoke about this a few months back. A minimal test case of the failure is here:
https://github.com/kubernetes-sigs/kustomize/pull/1316#issuecomment-510456989

For more context, I have one file that contains all environment specific identifiers that is generated at the time the cluster is created (by Terraform). Here is a sample:
```
# GENERATED BY TERRAFORM
apiVersion: v1
kind: ConfigMap
metadata:
  name: environment
data:
  hostname: <OMITTED>
  rds_ci_hostname: <OMITTED>
  rds_statestore_hostname: <OMITTED>
  kiam_server_sudosu_role: <OMITTED>
  secret_prefix: <OMITTED>
  ci_secret_prefix: <OMITTED>
  app_secret_prefix: <OMITTED>
  rds_secret_prefix: <OMITTED>
  aws_region: us-east-1
```

Sibling to this file I have the following:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - environment.yml
```

...every single kustomization file in my configuration references this common base. 
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../config/
  - ../../../../../../../shared/kubernetes/monitoring/loki
```

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../../config
  - ../../../../../../shared/kubernetes/kiam/
```

If I apply these individually everything is fine. However, I do have one master kustomization.yml I'd like to be able to apply that I cannot (due to the failure shared in the link above).
```
# This file is here for the convenience of building multiple configurations with
# a single command. No customizations should be placed here as they will not be
# available if/when projects are configured independently.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bootstrap.yml
  - manifests/cert-manager
  - manifests/concourse
  - manifests/dns-autoscaler
  - manifests/ingress-nginx
  - manifests/kiam
  - manifests/monitoring
  - manifests/service-catalog
```

It makes sense to me that references to `$(ConfigMap.environment.data.<field>)` would fail because it is unable to disambiguate between each that appear, but each is exactly the same save for the namespace field. It seems like this sort of conflict should be self-resolving?

**Comment by jbrette** [comment]
This PR was only doing automatically what user have to painfully do by hand. Since it was specified in will never be merged, closing it and keeping private.

**Comment by jonathanunderwood** [comment]
This is a really disappointing outcome.

**Comment by oboukili** [comment]
So much work and energy had been put into this, that's really sad.

**Comment by jbrette** [comment]
The code is not lost for our project and will stay in our fork. The design of this  PR is to create whatever complex structure kustomize uses at the time. (currently varRef and var). Once the Replacement PR is merged, we will only have to adapt the autovar feature. Indeed that Replacement PR still forces the user to manually create complex fieldspecs in the kustomization.yaml. 

Actually from a selfish point of view, it means that our project does not have to keep the PR small anymore or rebase to allow easier merging. With the four true features PR (diamond, inline, autovar and transformers), we unfortunatly end up with a fork of kustomize,  but a least that fork gets everything much more simplier for our users (and still uses the same kustomization.yaml as the official kustomize). The real game changer in the fork/nofork debat was the handling of SMP instead JMP for CRD by kustomize (CRD are everywhere in the new applications: Istio, Argo, Prometheus, OpenShift, Cluster-API,.) .

Still fork is able to address 90% of the issues raised, some of them having been opened more than a year [check here](https://github.com/keleustes/kustomize/tree/allinone/examples/issues)

**Comment by jonathanunderwood** [comment]
@jbrette what is the "Replacement PR" you refer to?

**Pull request closed without merging**
