### PR TITLE
Docs Update - patches

### PR DESCRIPTION
**Pull request by SyamSundarKirubakaran**
This PR adds examples to `patches` under API Reference.

/ PR is a part of Google Season of Docs 2020

cc: @pwittrock

### CODE REVIEW

**Comment by SyamSundarKirubakaran** [comment]
I signed it

**Comment by monopole** [comment]
@SyamSundarKirubakaran something is off with the signature.
Please review https://github.com/kubernetes-sigs/kustomize/pull/2892#issuecomment-680857937

Usually this is a mis-match of email addresses.

**Comment by SyamSundarKirubakaran** [comment]
I signed it

**Pull request merged**
