### PR TITLE
#2214 : Variable reference does not work on the nfs.server 

### PR DESCRIPTION
**Pull request by giteshk**
This pull request addresses #2214

### CODE REVIEW

**Comment by pwittrock** [comment]
Would you also update the data for other Resource types -- e.g. StatefulSet, Job, DaemonSet?

**Comment by giteshk** [comment]
@pwittrock let me add support for StatefulSet, Job, DaemonSet, CronJob.

Can you think of any others?

**Comment by pwittrock** [comment]
everything with a PodSpec -- ReplicaSet, ReplicationController,Pod,CronJob,PodTemplate

**Comment by pwittrock** [comment]
@giteshk You want to add those to this PR, or as a follow up?

**Comment by giteshk** [comment]
@pwittrock I will add them to this PR. 
Sorry got distracted for the past few days, had to concentrate on some internal process :) 

But I will try to get these in this week.

**Comment by pwittrock** [comment]
SGTM; no rush.  If something comes up that will delay you for more than a week, we can take the PR as is and follow up with another.

**Comment by giteshk** [comment]
@pwittrock This is ready for review.

**Comment by pwittrock** [comment]
@giteshk Thanks, there are a couple things going on that got me underwater.  Will TAL early next week if that is alright.

**Pull request merged**
