### PR TITLE
Remove unused IsFieldEmpty function, add more godoc.

### LINKED ISSUE #2809: Refactor IsEmpty/IsMissingOrNull/IsEmptyMap/IsNull in kyaml/yaml/types.go
https://github.com/kubernetes-sigs/kustomize/pull/2805#discussion_r466768984

### PR DESCRIPTION
**Pull request by monopole**
kpt not using this function.
Fixes #2809 (seems like enough).

### CODE REVIEW

**Comment by monopole** [comment]
@Shell32-Natsu

**Comment by Shell32-Natsu** [comment]
lgtm. Thanks a lot!

**Comment by phanimarupaka** [comment]
@monopole @Shell32-Natsu It's being used here https://github.com/kubernetes-sigs/kustomize/blob/master/cmd/config/internal/commands/cmdxargs.go#L180

**Comment by Shell32-Natsu** [comment]
@phanimarupaka Do you have to use a released version of `cmd/config`? I can make a fix pull request now.

**Pull request merged**
