### PR TITLE
Fix exec plugins on windows

### PR DESCRIPTION
**Pull request by jaysonsantos**
The exec plugin implementation checks if an executable file exists but
on windows it won't check for files with .exe suffix thus falling back
to go plugin implementation

### CODE REVIEW

**Comment by jaysonsantos** [comment]
Comment to verify cla

**Comment by jaysonsantos** [comment]
You can see it breaking here https://github.com/jaysonsantos/kustomize-sops-rs/pull/5
I am not sure on how and where to add the tests cases, could you point me out?

**Comment by Shell32-Natsu** [comment]
Doesn't #3027 resolve this problem?

**Comment by jaysonsantos** [comment]
Hey there, it does not. The only way to make it work is to have a file called Kind and then another one call Kind.exe so the file exists check works on the first one and then the exec call on windows, they try files with suffix exe, ps1, and bat and executes the last one

**Comment by Shell32-Natsu** [comment]
What if you add `.exe` suffix to the `Kind` in transformer config?

**Comment by jaysonsantos** [comment]
I guess it would work but should break if you run the same kustomize on non-windows machines

**Comment by monopole** [comment]
The code you're trying to work with is a bit of a mess.

Suggest adding a free standing function in the `loader.go` file like

```
func LookForExecutable(partialPath string) (fullPath string, err error) {
  // In here have all the os dependent stuff.
  // Try to confirm file existence and if it's executable, as a function of operating system.
  // If on windows, add the .exe extension, maybe .bat too, and see if the file exists.
  //   On windows, there's no exec bit, so just assume that if on windows and
  //   the file ends in .exe that it's executable. 
  // else (If not on windows)
  //   test the exec bit.
  // If everything works (the file exists, and appears to be executable) return path, nil.
  // if not, return "", error.
}
```

The above would totally replace the use of `p.ErrIfNotExecutable`, so delete it.  It's best
to not even create the ExecPlugin object unless it's known that an exec file exists.

The new flow would be just:
```
func (l *Loader) loadExecOrGoPlugin(resId resid.ResId) (resmap.Configurable, error) {
  path, err:= LookForExecutable(l.absolutePluginPath(resId))
  if err != nil {
    return execplugin.NewExecPlugin(path), nil
  }
  return l.loadGoPlugin(resId)
}
```

**Comment by jaysonsantos** [comment]
Hey there @monopole, could you check again?
I chose not to check the executable bit on the loader as the exec plugin already does it. Do you think that it makes sense to move out from exec plugin to loader?

**Comment by jaysonsantos** [comment]
Also, `lookForExecutable`s error is being ignored because it fallbacks to go plugin

**Comment by jaysonsantos** [comment]
Hey there folks, do you think this is useful?

**Comment by Shell32-Natsu** [comment]
@monopole

**Comment by jaysonsantos** [comment]
I am giving up on this.

**Pull request closed without merging**
