### PR TITLE
Update go 1.22.7

### PR DESCRIPTION
**Pull request by koba1t**
fix https://github.com/kubernetes-sigs/kustomize/issues/5762

### CODE REVIEW

**Comment by koba1t** [comment]
@varshaprasad96 
Please type the `retest` command after https://github.com/kubernetes/test-infra/pull/33478 is merged.

**Review by varshaprasad96 — APPROVED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
@koba1t Was the minimum go version intentionally bumped to 1.22.7? (instead of just 1.22.0)

We have a dependency to kyaml and the minimum go version in the kyaml go.mod file would now force us to also require 1.22.7 as min version

**Comment by koba1t** [comment]
@sbueringer 

Sorry, I just wanted to use go >= 1.22.0.
However, I feel that it is hard to downgrade the golang version of this project.

If it is acceptable, can you wait to upgrade kyaml until `kubernetes-sigs/cluster-api-provider-vsphere` is upgraded to go 1.23?

**Comment by sbueringer** [comment]
> Sorry, I just wanted to use go >= 1.22.0.

No worries.

> If it is acceptable, can you wait to upgrade kyaml until kubernetes-sigs/cluster-api-provider-vsphere is upgraded to go 1.23?

Talked to @chrischdi. We're fine we have ways to work around it.

> However, I feel that it is hard to downgrade the golang version of this project.

For us it's okay to keep it as is. Just one note for the future. There is a difference between the Go version that is used to compile a module and the minimium go version ("go 1.22.7") defined in the go.mod file. The latter forces everyone that imports the module to:
* also require a minimum go version of >= 1.22.7
* compile with at least Go 1.22.7

This affects everyone who has a transitive dependency on a module.

E.g. controller-runtime chose because of that to only require 1.22.0 in their go module: https://github.com/kubernetes-sigs/controller-runtime/blob/v0.18.5/go.mod

So overall I would just recommend going forward to use `.0` versions in the go.mod file. You can still use a higher Go patch version for running unit tests, compiling binaries etc.

**Comment by chrischdi** [comment]
Note: For fixing the linked issue it should have been enough to bump the go version used for compiling and keep the `go 1.21`. That would even be cherry-pickable to branches for patch releases.

Still okay I think to bump the directive to e.g. `go 1.22.0` for a next minor release.

**Pull request merged**
