### PR TITLE
update zh doc api-reference/kustomization/patches

### PR DESCRIPTION
**Pull request by sunny0826**
update zh doc
based on：https://github.com/kubernetes-sigs/kustomize/commit/fbebd990a4086c967f741ae2d7fd29a24b59845e#diff-c564ac31146ea183dfe2f37b5dde5965

### CODE REVIEW

**Comment by sunny0826** [comment]
Preview Address: https://sunny0826.github.io/kustomize/zh/api-reference/kustomization/patches/

**Comment by Liujingfang1** [comment]
/lgtm

Delegate @monopole to approve it

**Pull request merged**
