### PR TITLE
Add dependency: github.com/hashicorp/go-getter

### PR DESCRIPTION
**Pull request by Liujingfang1**

### CODE REVIEW

**Comment by monopole** [comment]
3000 files!?!?!?!?!?

**Comment by monopole** [comment]
This is too much, somethings wrong, or their package literally sucks :)

**Comment by Liujingfang1** [comment]
Manually remove `github.com/aws` from both vendor directory and Gopkg.lock

**Comment by monopole** [comment]
ok to unblock.  we can re-evaluate deps later.

**Pull request merged**
