### PR TITLE
feat: add CheckDiffOnFile in git module on gorepomod

### PR DESCRIPTION
**Pull request by antoooks**
- Add `CheckDiffOnFile` function on git module to check diff
- Add tests for `CheckDiffOnFile`

### CODE REVIEW

**Comment by antoooks** [comment]
Hi @natasha41575 , would you care to elaborate how to access `git` modules on `gorepomod` from Makefile? Do I need to release it before so?

**Comment by antoooks** [comment]
> Hi @natasha41575 , would you care to elaborate how to access `git` modules on `gorepomod` from Makefile? Do I need to release it before so?

hi @koba1t, seeking your advice, and maybe you know stuff about this module. Since we use go modules I think this module (`gorepomod`) may not work anymore with the current repo state right? 

In that case I should go with a simpler option by executing the diff checking on Makefile directly

**Comment by koba1t** [comment]
Hi @antoooks
Thanks for your contribution.
I'm not familiar with this problem and don't know why you added this function.
So, Could you add any context as to why you made this PR or add a link for the issue that you want to resolve?

**Comment by antoooks** [comment]
> Hi @antoooks Thanks for your contribution. I'm not familiar with this problem and don't know why you added this function. So, Could you add any context as to why you made this PR or add a link for the issue that you want to resolve?

@koba1t Yes, absolutely! This PR is part of two PRs that addresses issue #4977, the other one being #5303. In the comment, I presented 2 ways of integrating the diff check, then on the previous standup meeting, it is decided that we should try option 2 of implementing the diff check with a separate module, @natasha41575 suggested that I should implement it in `gorepomod` module because they have collections of git commands that the repo is using. However we also conclude that if we sees that this option is unsuitable we should go with option 1 which means we implement everything using simple command on Makefile. Let me know if you need anymore on the context :)

**Comment by antoooks** [comment]
Closing, as we have settled into implementing all checks on Makefile instead. Refer to https://github.com/kubernetes-sigs/kustomize/pull/5303

**Pull request closed without merging**
