### PR TITLE
fix(examples): move examples from patchesStrategicMerge to patches

### LINKED ISSUE #5200: Migrate exmaples from `patchesStrategicMerge` to `patches`
### Eschewed features

- [X] This issue is not requesting templating, unstuctured edits, build-time side-effects from args or env vars, or any other eschewed feature.

### What would you like to have added?

Clean up referenfces for `patchesStrategicMerge` by replacing them with `patches`

### Why is this needed?

`patchesStrategicMerge` was removed in >=5.0.0 (via https://github.com/kubernetes-sigs/kustomize/pull/4911)

### Can you accomplish the motivating task without this feature, and if so, how?

not in >= 5.0.0

### What other solutions have you considered?

N/A

### Anything else we should know?

_No response_

### Feature ownership

- [X] I am interested in contributing this feature myself! 🎉

### PR DESCRIPTION
**Pull request by danistrebel**
Fixes #5200 to move the examples to the new patches model

### CODE REVIEW

**Comment by koba1t** [comment]
Hi @ncapps

Could you review this PR?
I feel this PR is in the area of documentation.

**Comment by ncapps** [comment]
Thank you for your contribution!

/lgtm

**Comment by ncapps** [comment]
Hi @koba1t , Would you please review and provide approval when you get a chance?

**Comment by koba1t** [comment]
Thanks!
/approve

**Pull request merged**
