### PR TITLE
modify pluginator to support convert builtin plugin to krm function

### PR DESCRIPTION
**Pull request by Shell32-Natsu**

### CODE REVIEW

**Comment by monopole** [comment]
Can you think of ways to make this pr smaller?

**Comment by Shell32-Natsu** [comment]
will do

**Comment by monopole** [comment]
e.g. rnodeListToResMap(r []*kyaml.RNode) (resmap.ResMap) could be a method on rnode.
it can go away later when we ditch resmap.

**Comment by monopole** [comment]
..in a distinct pr with a test - just for rnode.

**Comment by Shell32-Natsu** [comment]
I think that's not possible since ResMap is in api and api depends on kyaml.

**Comment by Shell32-Natsu** [comment]
cc @droot @frankfarzan

**Review by monopole — COMMENTED** [review]
please move all the ancillary packages down into internal,
so you don't have to worry about anyone depending on them.
See code arrangement in gorepomod.

**Comment by monopole** [comment]
/lgtm
thanks!

**Pull request merged**
