### PR TITLE
Replace language with more inclusive & accurate "hard-coded"

### PR DESCRIPTION
**Pull request by justinsb**
hard-coded is probably more helpful to understanding the limitations of the current approach.

### CODE REVIEW

**Comment by justinsb** [comment]
Maybe this comment should be moved to IsNamespaceableKind ?

**Comment by phanimarupaka** [comment]
@justinsb Thanks for the PR. We should also replace terminology like master-slave with primary-secondary or equivalent.

**Comment by justinsb** [comment]
Agree @phanimarupaka ... I came across this particular instance when looking into how this logic worked.  Happy to send additional PRs; the master/slave term seems only to be in some testdata so that should be fairly straightforward!

**Comment by justinsb** [comment]
(I actually had a look, it's possible to remove some of the terminology but some of it is determined by MySQL which hasn't provided alternative terms yet: https://bugs.mysql.com/bug.php?id=99806 )    As it's only a test, it might not actually matter, but it might also be very confusing to have a real-world but broken example.

**Pull request merged**
