### PR TITLE
Fix helm globals

### PR DESCRIPTION
**Pull request by sonthonaxrk**
https://github.com/kubernetes-sigs/kustomize/issues/4298

Fixes this issue.

### CODE REVIEW

**Comment by natasha41575** [comment]
/ok-to-test
/approve
/lgtm

Please sign the CLA!

**Comment by sonthonaxrk** [comment]
Hey @natasha41575 I've signed the CLA.

Screenshot 2022-01-07 at 11 35 55

**Comment by natasha41575** [comment]
Please make sure the email you've signed the CLA with is set on your commits. You can see some instructions here https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-email-preferences/setting-your-commit-email-address

**Comment by sonthonaxrk** [comment]
@natasha41575 hey natasha, I've amended the commit with the correct email. 

Still missing the easycla auth

**Pull request merged**
