### PR TITLE
Update set.md examples to use correct field name

### PR DESCRIPTION
**Pull request by dan-slinky-ckpd**

### CODE REVIEW

**Comment by dan-slinky-ckpd** [comment]
I signed it

**Comment by pwittrock** [comment]
@dan-slinky-ckpd thanks for the fix.  the Kustomize docs are really out of date for these commands, and the  https://googlecontainertools.github.io/kpt/ are more up-to-date.  need to figure out what we want to do re-docs for the kyaml related commands.

**Comment by pwittrock** [comment]
@phanimarupaka Are these docs correct?

**Pull request merged**
