### PR TITLE
Config map key order

### PR DESCRIPTION
**Pull request by gxwilkerson33**
Fixes: https://github.com/kubernetes-sigs/kustomize/issues/4292

### CODE REVIEW

**Comment by gxwilkerson33** [comment]
/cc @natasha41575
/cc @KnVerey 
CC'ing the above as they have commented on previous PRs of this same issue. Thanks

**Comment by charles-chenzz** [comment]
hi @gxwilkerson33 , are you still planning to work on this? if so please rebase, if not I would like to take on this

**Comment by charles-chenzz** [comment]
/close
in favor of #5308

**Pull request closed without merging**
