### PR TITLE
pass loader root to exec plugins

### PR DESCRIPTION
**Pull request by Liujingfang1**

### CODE REVIEW

**Comment by pwittrock** [comment]
Can we add a test?

**Comment by monopole** [comment]
test pls

**Comment by Liujingfang1** [comment]
Added a test with an executable as
```
dir=`pwd`

echo "
kind: WorkDir
apiVersion: v1
metadata:
  name: $dir
"
```

The test ensures that the output matches with the loader root.

**Comment by Liujingfang1** [comment]
fixed the test. PTAL @monopole @pwittrock

**Comment by pwittrock** [comment]
Would you test KUSTOMIZE_PLUGIN_CONFIG_ROOT as well

**Pull request merged**
