### PR TITLE
Rename cmd/kyaml to cmd/config

### PR DESCRIPTION
**Pull request by joncwong**
#1802

### CODE REVIEW

**Comment by haiyanmeng** [comment]
You need to rename `cmd/kyaml` to `cmd/config`, and update the path in `travis/kyaml-pre-commit.sh` and `./travis/verify-deps.sh`.

**Comment by joncwong** [comment]
> You need to rename `cmd/kyaml` to `cmd/config`, and update the path in `travis/kyaml-pre-commit.sh` and `./travis/verify-deps.sh`.

Fixed! Thanks for the catch!

**Pull request merged**
