### PR TITLE
fixes issue with windows release binary name #5410

### PR DESCRIPTION
**Pull request by bb-Ricardo**
This should solve the issue with binary suffixes for windows releases #5410.

### CODE REVIEW

**Comment by charles-chenzz** [comment]
can you sign the CLA so that we can process your PR?
https://github.com/kubernetes-sigs/kustomize/pull/5415#issuecomment-1776903912

**Comment by bb-Ricardo** [comment]
> can you sign the CLA so that we can process your PR? [#5415 (comment)](https://github.com/kubernetes-sigs/kustomize/pull/5415#issuecomment-1776903912)

Currently awaiting internal approval

**Comment by bb-Ricardo** [comment]
The approval has been given but not sure how to trigger the check again.

**Comment by natasha41575** [comment]
@bb-Ricardo The CLA check should automatically update. Can you make sure the commits on here are associated with the email address that you signed the CLA with? If they are, you might have to follow the links in https://github.com/kubernetes-sigs/kustomize/pull/5415#issuecomment-1776903912 for further troubleshooting.

**Comment by bb-Ricardo** [comment]
> @bb-Ricardo The CLA check should automatically update. Can you make sure the commits on here are associated with the email address that you signed the CLA with? If they are, you might have to follow the links in [#5415 (comment)](https://github.com/kubernetes-sigs/kustomize/pull/5415#issuecomment-1776903912) for further troubleshooting.

I have followed the link as a corporate contributor, requested approval from our CLA Manager, filled in details and send the form. Then I asked our CLA Manager and he said he approved the request. If I follow the link again I can only restart the same process.

**Comment by natasha41575** [comment]
@bb-Ricardo I'm sorry, but there isn't really anything we can do to help if the CLA check isn't recognizing your username - this is a requirement from CNCF. Are you certain that the commits are associated with the email that has the CLA authorization? If so, then the only thing you can do from there is [file a support ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4)

**Comment by bb-Ricardo** [comment]
Hey,

I don't actually care who submits this PR. If you have someone, just grab the commit, close the PR and submit a new PR.

Really can't be bothered with all this fuss for these view lines of code.

Would this be possible?

**Comment by bb-Ricardo** [comment]
And yes, my account is associated with two email addresses. Which one would be the relevant one?

**Comment by charles-chenzz** [comment]
@bb-Ricardo hi, I would try to pick up the commit and co-author you and submit a new PR. but it might require you to track on that PR. would it make sense to you?

**Comment by bb-Ricardo** [comment]
Sure, no problem

**Comment by charles-chenzz** [comment]
see #5439 think it's safe to close this one
/close

**Pull request closed without merging**
