### PR TITLE
Remove inventory transformer

### PR DESCRIPTION
**Pull request by Shell32-Natsu**
Remove inventory and update related documentations.

### CODE REVIEW

**Comment by Shell32-Natsu** [comment]
Signed CLA

**Comment by Shell32-Natsu** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> 📝 **Please follow instructions at https://git.k8s.io/community/CLA.md#the-contributor-license-agreement to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment and we'll verify. Thanks.
> 
> * If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your [email is set on your git commits](https://help.github.com/articles/setting-your-email-in-git/).
> * If you signed the CLA as a corporation, please sign in with your organization's credentials at https://identity.linuxfoundation.org/projects/cncf to be authorized.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please log a ticket with the Linux Foundation Helpdesk: https://support.linuxfoundation.org/
> * Should you encounter any issues with the Linux Foundation Helpdesk, send a message to the backup e-mail support address at: [login-issues@jira.linuxfoundation.org](mailto:login-issues@jira.linuxfoundation.org)

Retry

**Comment by Shell32-Natsu** [comment]
I signed it

**Comment by Liujingfang1** [comment]
You may need to change the author for the commits
`git commit --amend --author="Author Name <email@address.com>"`

**Comment by Shell32-Natsu** [comment]
The email address is correct in the commits.

```
commit 96f907209ee442896f10630ea0f7f11866e9302f (HEAD -> 2392-codeClean, origin/2392-codeClean)
Author: Donny Xia <donnyxia@google.com>
Date:   Mon Apr 27 11:32:10 2020 -0700

    Update document

commit 515ad0a9538f73ea80a47e08b43b4a552151faf1
Author: Donny Xia <donnyxia@google.com>
Date:   Wed Apr 22 16:56:16 2020 -0700

    Remove inventory transformer #2392
```

**Comment by Shell32-Natsu** [comment]
I guess I need to click the "signup to contribute" link again on this [page](https://identity.linuxfoundation.org/projects/cncf)

**Comment by Shell32-Natsu** [comment]
Well that works.

**Comment by monopole** [comment]
This sign up flow could use some improvement :P 

/lgtm

Special thanks to @Liujingfang1 for implementing this design, as it greatly informed the approach being built into client side apply.

**Comment by Shell32-Natsu** [comment]
Thanks!

**Pull request merged**
