### PR TITLE
Fix two broken deps to allow tests under hack/crawl to pass

### PR DESCRIPTION
**Pull request by haiyanmeng**
1) copy api/internal/git to hack/crawl/crawler/: internal packages are 
not allowed to be imported;
2) change the import path from api/pgmconfig to api/kconfig

make sure `go build` and `go test` pass;

run `go mod tidy` to clean up go.sum;

### CODE REVIEW

**Comment by mengqiy** [comment]
@haiyanmeng  Travis CI doesn't respect "/retest"

**Comment by haiyanmeng** [comment]
The travis failure does not seem to relate to this PR:
```
$ ./travis/pre-commit.sh
...
cd api; /home/travis/go/bin/golangci-lint run ./...
ERRO Running error: context loading failed: failed to load program with go/packages: -: go: downloading sigs.k8s.io/kustomize/pseudo/k8s v0.1.0
...
The command "./travis/pre-commit.sh" exited with 2.
```

**Pull request merged**
