### PR TITLE
add edit remove component command

### PR DESCRIPTION
**Pull request by vvatlin**
I would like to add "edit remove component" command 
https://github.com/kubernetes-sigs/kustomize/issues/5103

### CODE REVIEW

**Comment by koba1t** [comment]
This PR looks good to me!

/lgtm

**Comment by TobKed** [comment]
Thanks @vvatlin for you contribution 🙇‍♂️ 🚀 . 
I was just looking for this feature. What we can do to push this @natasha41575 @KnVerey @annasong20 @koba1t ?

**Comment by rybnico** [comment]
I also miss this feature. We're using `kustomize edit` for our git-based deployments and currently need a `sed` workaround to remove components.
Any chance of getting this PR merged? I can also offer my support if something needs to be done.

**Comment by annasong20** [comment]
Really sorry for the delay. Kustomize is currently running a maintainer training cohort. Hopefully by the end of it we'll have more maintainers to approve PRs.

**Pull request closed without merging**
