### PR TITLE
upgrade admissionregistration.k8s.io/v1beta1 version to v1

### PR DESCRIPTION
**Pull request by JaredTan95**
upgrade admissionregistration.k8s.io/v1beta1 version to v1

Signed-off-by: JaredTan95 <jian.tan@daocloud.io>

### CODE REVIEW

**Comment by Shell32-Natsu** [comment]
The CI failure is because of your commit is crossing multiple modules.

**Comment by JaredTan95** [comment]
> The CI failure is because of your commit is crossing multiple modules.

Do I need to commit two PR separately when across modules?

**Pull request closed without merging**
