### PR TITLE
use default helm env config

### PR DESCRIPTION
**Pull request by wuxingzhong**

### CODE REVIEW

**Review by monopole — APPROVED** [review]
/ok-to-test
/lgtm

**Comment by monopole** [comment]
@wuxingzhong  please take a look at this: https://docs.github.com/en/github/committing-changes-to-your-project/why-are-my-commits-linked-to-the-wrong-user

**Comment by wuxingzhong** [comment]
sign the CLA  check.

**Comment by wuxingzhong** [comment]
verify CLA

**Comment by wuxingzhong** [comment]
@k8s-ci-robot  verify CLA

**Comment by natasha41575** [comment]
@wuxingzhong it looks like your commit is still not connected to your github account. Please take another look at the link that @monopole commented

**Pull request closed without merging**
