### PR TITLE
Remove dependency on ghodss/yaml

### PR DESCRIPTION
**Pull request by rohitsardesai83**
xref : https://github.com/kubernetes/kubernetes/issues/77024
Replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`

### CODE REVIEW

**Comment by dims** [comment]
/assign @monopole @Liujingfang1 

yes please! this will help us remove the ghodss/yaml dependency from main kubernetes repository.

**Comment by rohitsardesai83** [comment]
Updated the comment as per suggestion. Thanks

**Comment by neolit123** [comment]
thanks
/hold cancel

**Comment by dims** [comment]
/assign @justinsb @pwittrock 

Justin, Phillip, easy one, can you please approve?

**Comment by dims** [comment]
related to https://github.com/kubernetes/kubernetes/issues/77024

**Pull request merged**
