### PR TITLE
WIP: Windows Pre-Commit

### PR DESCRIPTION
**Pull request by kenmaglio**
Done:
- Invoke-PreCommit.ps1 added to bin
  - After prereqs installed ( see the function in the file to assist ) was able to run same commands as Linux

Working:
- How do we automate this in Travis if possible like the Linux side does today?

Results:
- Linting passes
- Tests do not pass
- Mdrip passes
  - NOTE: If this is run multiple times in a session, something with this package locks a file in windows and fails the run.

### CODE REVIEW

**Comment by monopole** [comment]
@kenmaglio can you add _total noob_ instructions to the top of this file as to how to run this on a stock windows 10 box?

**Comment by kenmaglio** [comment]
@monopole Yeah I can do

**Comment by kenmaglio** [comment]
@monopole Check out the document (MD)  -- Thoughts?

**Comment by kenmaglio** [comment]
Currently mdrip has an issue ( race condition? )

```
============== begin Test-Examples
F0305 11:25:19.498657   23076 util.go:41] delete temp file: remove C:\Users\magliok\AppData\Local\Temp\mdrip-file-128995271: 
The process cannot access the file because it is being used by another process.
goroutine 1 [running]:
github.com/monopole/mdrip/vendor/github.com/golang/glog.stacks(0xc000299d00, 0xc000245860, 0xcd, 0xe4)
        C:/_go/src/github.com/monopole/mdrip/vendor/github.com/golang/glog/glog.go:769 +0xdb
github.com/monopole/mdrip/vendor/github.com/golang/glog.(*loggingT).output(0xbe8540, 0xc000000003, 0xc000106580, 0xba5633, 0x7, 0x29, 0x0)
        C:/_go/src/github.com/monopole/mdrip/vendor/github.com/golang/glog/glog.go:720 +0x324
github.com/monopole/mdrip/vendor/github.com/golang/glog.(*loggingT).printDepth(0xbe8540, 0xc000000003, 0x1, 0xc0000e7cd8, 0x1, 0x1)
        C:/_go/src/github.com/monopole/mdrip/vendor/github.com/golang/glog/glog.go:646 +0x130
github.com/monopole/mdrip/vendor/github.com/golang/glog.(*loggingT).print(0xbe8540, 0x3, 0xc0000e7cd8, 0x1, 0x1)
        C:/_go/src/github.com/monopole/mdrip/vendor/github.com/golang/glog/glog.go:637 +0x61
github.com/monopole/mdrip/vendor/github.com/golang/glog.Fatal(0xc0000e7cd8, 0x1, 0x1)
        C:/_go/src/github.com/monopole/mdrip/vendor/github.com/golang/glog/glog.go:1128 +0x5a
github.com/monopole/mdrip/util.Check(0x88e6ed, 0x10, 0x905760, 0xc000304060)
        C:/_go/src/github.com/monopole/mdrip/util/util.go:41 +0xa8
github.com/monopole/mdrip/subshell.(*Subshell).Run.func1(0xc000092760)
        C:/_go/src/github.com/monopole/mdrip/subshell/subshell.go:229 +0x63
github.com/monopole/mdrip/subshell.(*Subshell).Run(0xc0000e7e90, 0xc000358000)
        C:/_go/src/github.com/monopole/mdrip/subshell/subshell.go:281 +0x43d
main.trueMain(0xc0000653e0, 0x0, 0x0)
        C:/_go/src/github.com/monopole/mdrip/main.go:42 +0x46f
main.main()
        C:/_go/src/github.com/monopole/mdrip/main.go:70 +0x5b
============== end Test-Examples : FAILURE code=False
```

**Pull request closed without merging**
