### PR TITLE
docs: add favicons

### PR DESCRIPTION
**Pull request by loffing**
Addresses https://github.com/kubernetes-sigs/kustomize/issues/5312 by adding favicons based on [those used on kustomize.io ](https://github.com/replicatedcom/kustomize-www/tree/main/themes/replicated-docs-theme/static/favicons)

### CODE REVIEW

**Review by charles-chenzz — COMMENTED** [review]
the typos was good catch! Thank you
but when I manually check kustomize.io I seen the icon is already replace, which site that this PR trying to add favicons?
image

**Comment by loffing** [comment]
@charles-chenzz Thanks for the review!

As @natasha41575 mentioned [here](https://github.com/kubernetes-sigs/kustomize/issues/5312#issuecomment-1783203160), the issue associated with this PR is concerned with the `site` directory in this repo, not the current kustomize.io.

My understanding is that the long-term goal is to replace the current content at kustomize.io with the content of the `site` directory, as described in https://github.com/kubernetes-sigs/kustomize/issues/4338.

**Comment by charles-chenzz** [comment]
> @charles-chenzz Thanks for the review!
> 
> As @natasha41575 mentioned [here](https://github.com/kubernetes-sigs/kustomize/issues/5312#issuecomment-1783203160), the issue associated with this PR is concerned with the `site` directory in this repo, not the current kustomize.io.
> 
> My understanding is that the long-term goal is to replace the current content at kustomize.io with the content of the `site` directory, as described in #4338.

Thanks for clarifying it!

>If you are looking at kustomize.io, that is the site that we are trying to replace and is unrelated to the site directory that is sitting in this repo

I misunderstood this sentence. 

one more question: the pixel that you set, have you tried it locally?

**Comment by loffing** [comment]
Yep, I verified the new icons by running `hugo serve` locally.

**Comment by loffing** [comment]
@charles-chenzz Any other questions/feedback?

**Comment by charles-chenzz** [comment]
Generally lgtm to me(was on vacation sry)
/lgtm

T. Cheyney Loffing ***@***.***>于2023年12月31日 周日10:57写道：

**Pull request closed without merging**
