### PR TITLE
replace Resource.refBy with annotations

### PR DESCRIPTION
**Pull request by natasha41575**
fixes https://github.com/kubernetes-sigs/kustomize/issues/3976

### CODE REVIEW

**Comment by natasha41575** [comment]
Converting to draft because I just read in the original issue that we want tests for name references applied with KRM functions. Will add these in a bit

**Review by KnVerey — APPROVED** [review]
/lgtm

**Comment by rishabh625** [comment]
since this change adds config.kubernetes.io/refBy annotation , other annotations value is not getting replaced

**Pull request merged**
