### PR TITLE
Write individual files to output path if it is a directory

### PR DESCRIPTION
**Pull request by zeeZ**
I created this to solve #897 before noticing #929 and am posting this to maybe offer a simpler alternative.

Current behaviour for `-o` is to complain if the path is a directory, so I simply changed that to write the individual files (based on the final resource) there instead.

I did not include namespace in the file name because neither `ResId.GvknString()` nor `Gvk.String()` include it and I didn't want to write that function a third time and didn't feel the need for it because namespace is usually also set once per build. If it's deemed necessary I'll add it.

### CODE REVIEW

**Comment by monopole** [comment]
This follows the suggestion in #897, but doesn't do what the requestor wants, i.e.
> I need to reproduce an exact file layout as it is needed for our purposes.

Does anyone else want the output split into gvkn.yaml files?

**Comment by zeeZ** [comment]
There is also #55 with two people wanting split files, though the initial request was also for writing out following the input names. I guess I'm trying to solve neither OP, but the comments, with predictable file names.

**Comment by sidps** [comment]
I presume this will be in the next release? If so, when will that be?

**Comment by pdefreitas** [comment]
I am wondering when this will be released.

**Pull request merged**
