### PR TITLE
fix: use k8syml.YAMLToJSON when marshalling resources

### PR DESCRIPTION
**Pull request by dwalters**
Better handles cases where the YAML is not valid JSON, such as
maps with integer keys (#3446).

### CODE REVIEW

**Review by ijsong — APPROVED** [review]

**Comment by dwalters** [comment]
Looks like `YAMLToJSONStrict` prohibits duplicate keys, though the error message is slightly different, assume that's OK.

Also removed the special case for lists that was added in 802d79a, since k8syaml handles that as well.  The test from that commit passes.

**Comment by Raffo** [comment]
@natasha41575 any update on this one? #3446 is hitting us as well.

**Comment by dwalters** [comment]
As far as I know this is good to go, happy to address any concerns..

**Comment by wibed** [comment]
please kindly reopen, hitting this one

**Pull request closed without merging**
