### PR TITLE
Consider stringData when calculate secret hash

### PR DESCRIPTION
**Pull request by Shell32-Natsu**
https://github.com/kubernetes-sigs/kustomize/issues/2466

### CODE REVIEW

**Comment by Liujingfang1** [comment]
Overall, the change looks good to me. I'm curious is there any way to generate stringData by secretGenerator?

**Comment by Shell32-Natsu** [comment]
https://github.com/kubernetes-sigs/kustomize/blob/c4db0f9a603ec6c73983653bf1b466bce31afee3/api/internal/k8sdeps/configmapandsecret/secretfactory.go#L45-L54

Seems that the data will be only added to `data`

**Comment by Liujingfang1** [comment]
I see. So the change is to enable other generator plugins to use this field.

/ok-to-test
/lgtm

**Pull request merged**
