### PR TITLE
support multiple gvks in custom openapi schema

### PR DESCRIPTION
**Pull request by natasha41575**
Fix https://github.com/kubernetes-sigs/kustomize/issues/4127

ALLOW_MODULE_SPAN

### CODE REVIEW

**Comment by KnVerey** [comment]
How much trouble would it be to add a regression test based on the example provided in the issue?

**Comment by natasha41575** [comment]
> How much trouble would it be to add a regression test based on the example provided in the issue?

I added a regression test that verified multiple GVKs are supported, though instead of being specifically based on the example provided in the issue, it is based on the other examples we have in our custom OpenAPI schema tests.

**Pull request merged**
