### PR TITLE
deps: bump dependencies to latest for kyaml

### PR DESCRIPTION
**Pull request by howardjohn**
This bumps up dependencies to their latest. There is one trivial change in treeprint, changing nbsp to normal spaces; this should have no perceived impact to users.

ALLOW_MODULE_SPAN

### CODE REVIEW

**Comment by natasha41575** [comment]
Please fix the errors, they don't look major. LMK if you have trouble finding or deciphering the error output in the CI checks.

**Comment by howardjohn** [comment]
Seems like the tests require that I update all go modules `go.sum`, and also tell me I need 1 commit-per-module. Not worth the effort...

**Comment by natasha41575** [comment]
> also tell me I need 1 commit-per-module

Not actually true, I'll rerun the tests to see if they pass now

**Comment by natasha41575** [comment]
Actually, I'll bump these in a separate PR. I think there are some `go mod tidy`s that need to be run. Thanks for trying.

**Pull request closed without merging**
