### PR TITLE
fix: windows tests

### PR DESCRIPTION
**Pull request by alexeldeib**
totally meant to open this against my fork for testing, whoops. The tests work pretty easily though, so it's mostly tweaking the Travis config.

### CODE REVIEW

**Comment by alexeldeib** [comment]
cc @monopole

**Comment by alexeldeib** [comment]
thanks @kenmaglio for doing the hard work here on the script 😃

**Comment by kenmaglio** [comment]
@alexldeib of course!

**Comment by alexeldeib** [comment]
#834

**Comment by alexeldeib** [comment]
Documenting current test failures:

- looks like filepath cleaning
  - https://travis-ci.org/kubernetes-sigs/kustomize/jobs/586413083#L636-L643
  - https://travis-ci.org/kubernetes-sigs/kustomize/jobs/586413083#L719-L723
  - https://travis-ci.org/kubernetes-sigs/kustomize/jobs/586413083#L1173-L1181
  - https://travis-ci.org/kubernetes-sigs/kustomize/jobs/586413083#L1191-L1215
  - (long one) https://travis-ci.org/kubernetes-sigs/kustomize/jobs/586413083#L1295-L1618
- `config_test.go:85: default configurations are not successfully save.`
  - https://travis-ci.org/kubernetes-sigs/kustomize/jobs/586413083#L1072-L1075
- maybe something weird here with slashes? uncertain
  - https://travis-ci.org/kubernetes-sigs/kustomize/jobs/586413083#L1129-L1149
- travis go path issues (lots of these)
  - https://travis-ci.org/kubernetes-sigs/kustomize/jobs/586413083#L1235-L1249
  - https://travis-ci.org/kubernetes-sigs/kustomize/jobs/586413083#L1693-L1939
- unknown
  - https://travis-ci.org/kubernetes-sigs/kustomize/jobs/586413083#L1266-L1281
  - https://travis-ci.org/kubernetes-sigs/kustomize/jobs/586413083#L1674-L1676

@monopole or @richardmarshall if either of you are able to skim that list and tell me rough priority in terms of severity/fixes, that would be great.

**Comment by alexeldeib** [comment]
still need some travis config tweaking, but the build matrix is less crazy

**Comment by monopole** [comment]
Looks like mostly filepath stuff.  The real filesystem does a good job of converting between '/' and '\', but we have a fake to make the tests faster and avoid leaving state on disk.  can you rebase / rerun?

**Comment by alexeldeib** [comment]
I merged from upstream and re-ran last night, did I miss something? Or would you like me to squash?

I went through a few round with fakeFS behavior on windows, I'd like to get those clean (whether pre or post merge is fine with me). 

Also not sure how to make this optional for Windows?

**Comment by monopole** [comment]
looks abandoned

there's really no way get these test to run on windows without doing the grunt work on a test by test basis; hoping someone in the windows community can own this.  possibly things would get  better if the inmemoryfs were made less dependent on the path separator?

**Comment by alexeldeib** [comment]
Hi @monopole, I was originally waiting for a reply from you after my rebase, because I didn’t see any merge conflicts at the time. 

However, after looking through the fakeFS issues, I found another very large reason to stop working on this: plugin support.

This is directly related to a question I asked at the kustomize kubecon session yesterday (should’ve introduced myself, I was the tall redhead): plugin support on windows is entirely a non-starter due to execve and .so model.

I was really happy to hear that there is an alternative in the works that is container based and should work cross platform, because I’ve had a tough time figuring out how to align a windows implementation otherwise. I’d be happy to join any meetings Kustomize contributors hold to chat about this.

**Pull request closed without merging**
