### PR TITLE
[REVIEW] Feature/dockerjson docs

### PR DESCRIPTION
**Pull request by rosscdh**
Added docs for setting up a private repo regcred

### CODE REVIEW

**Comment by rosscdh** [comment]
I gotta say the whole signing the document linux foundation whooee... talk about a filter

**Comment by monopole** [comment]
the most common thing with the CLA is mismatch in email addresses
per https://github.com/kubernetes-sigs/kustomize/pull/1610#issuecomment-540390225

w/r to the PR, there should be a pointer to these instructions somewhere summarizing what they help with, e.g. in docs/README

**Comment by rosscdh** [comment]
In my case its probably the name. Didn't like apotrophe and lowercase
uppercase surnames converted to html.. shrug tbh the whole sign and commit
your spul show is a bit silly and puts me off wanting to contribute.

**Comment by pwittrock** [comment]
@rosscdh Sorry to hear that.  I'd prefer contributors not to jump through hoops as well.  

Unfortunately this is a requirement for all sub projects of Kubernetes, and unlikely to change.  If you have suggestions about how to improve the instructions, I can pass them on to the team that owns the cla bot and possibly update the bot help text.

**Comment by rosscdh** [comment]
@pwittrock the issue is the system does not match my name as it contains an apostrophe.. *shrug* I genuinely want to contribute to the docs but am blocked..

**Pull request closed without merging**
