### PR TITLE
Remove fix kustomization step before Unmarshalling the yaml structure

### PR DESCRIPTION
**Pull request by koba1t**
- Remove the [FixKustomizationPreUnmarshalling](https://github.com/kubernetes-sigs/kustomize/blob/f61b075d3bd670b7bcd5d58ce13e88a6f25977f2/api/types/fix.go#L12-L32) function.
- Move convert code for the deprecated field for `imageTags` to after unmarshalling.
- Show a warning message when using the `imageTags` at [this line](https://github.com/koba1t/kustomize/blob/8a99b753086f2084a64371242ad35b3d1364fa03/api/types/kustomization.go#L187).

This has already been talked about at https://github.com/kubernetes-sigs/kustomize/pull/4723#discussion_r944803795

## related PR
- https://github.com/kubernetes-sigs/kustomize/pull/4911

/cc @KnVerey @natasha41575

### CODE REVIEW

**Comment by natasha41575** [comment]
@koba1t when https://github.com/kubernetes-sigs/kustomize/pull/4918 is merged, could you rebase this PR? That PR makes a call to FixKustomizationPreUnmarshalling, but you can just remove those lines after you rebase and update any failing tests accordingly. Feel free to reach out if this isn't clear or if you run into any other problems with the `localizer` code.

**Comment by annasong20** [comment]
@koba1t In #4918, same PR that @natasha41575 mentions above, `images` in this line: https://github.com/kubernetes-sigs/kustomize/pull/4918/files#diff-c21f7b3d0afda4a64163411e90e72d2fed6c3df14c7b6f8ed07237bb5e1fc91cR213 also will also need to be changed to `imageTags`. Feel free to ping me with any problems.

**Review by natasha41575 — COMMENTED** [review]
/lgtm

**Pull request merged**
