### PR TITLE
Issue #2381 - bug fix for unmodified `found` variable

### PR DESCRIPTION
**Pull request by novalagung**
This PR should resolve the issue on https://github.com/kubernetes-sigs/kustomize/issues/2381

### CODE REVIEW

**Comment by novalagung** [comment]
CLA signed

**Comment by monopole** [comment]
/ok-to-test

nice find.

Would you be willing to modify the test to highlight this bug - i.e. add a test that fails without your fix?

Will take the PR anyway, but these examples need more tests.

**Comment by novalagung** [comment]
@monopole let me try it.

probably small question before I begin. currently, in this example, there is only one test scenario. should I modify the YAML string in the `input` and `output` to expect it will cover the line of code? or should I create another test scenario with new `input` and `output`?

**Pull request merged**
