### PR TITLE
draft: refactor: ci-task-improvement

### PR DESCRIPTION
**Pull request by antoooks**
- fix generate-kustomize-builtin-plugins
- add diff checker on generate-kustomize-builtin-plugins
- add `go work sync` on presubmit check
- add `generate-kustomize-builtin-plugins` on presubmit check

addresses #4977

### CODE REVIEW

**Comment by natasha41575** [comment]
@irvifa @koba1t There will be a new PR, so you can review that one when this is closed.

**Comment by irvifa** [comment]
@antoooks can you please make sure that you use the same email as what you use for the easycla on the github config?

**Comment by irvifa** [comment]
@antoooks if you close this PR please link the new PR which you'll use later on in favor of this one

**Comment by antoooks** [comment]
> @antoooks if you close this PR please link the new PR which you'll use later on in favor of this one

Will do on the new PR, thanks Vi @irvifa 

Closing this one

**Pull request closed without merging**
