### PR TITLE
mv /api/internal/target example to /api/krusty

### PR DESCRIPTION
**Pull request by Dingshujie**
related issue #1862

### CODE REVIEW

**Comment by monopole** [comment]
/lgtm
/approve

looks like travis ran the tests.

you should be able to run all tests locally by just entering `make`.

Thanks!

**Comment by Dingshujie** [comment]
> /lgtm
> /approve
> 
> looks like travis ran the tests.
> 
> you should be able to run all tests locally by just entering `make`.
> 
> Thanks!

@monopole  sorry, not familiar with this repo's development flow. i will do test locally

**Pull request merged**
