### PR TITLE
Update owners file

### PR DESCRIPTION
**Pull request by natasha41575**
- Move @natasha41575 and @annasong20 to emeritus
- @koba1t will be the new owner of kustomize! Congrats and thanks for stepping up.
- @ncapps will be a new docs approver
- @stormqueen1990 will be a new approver for the kustomize/kustomize directory (where all the commands live)
- @varshaprasad96 will be promoted to maintainer!

### CODE REVIEW

**Review by varshaprasad96 — APPROVED** [review]
/lgtm

**Comment by koba1t** [comment]
I appreciate your long contribution and helpful advice!
/lgtm

**Pull request merged**
