### PR TITLE
Remove dependency from cmd/config on cli-utils

### PR DESCRIPTION
**Pull request by mortent**
This removes the dependency from cmd/config on cli-utils. It is not used at the moment. I can update the PR to delete the file instead of commenting it out if that is preferable.

If we decide to put this back in, we should have the kustomize/kustomize module depend on cli-utils and not cmd/config. The current setup makes it hard for projects that depends on both modules to pull in changes from cli-utils.

### CODE REVIEW

**Comment by monopole** [comment]
Let's not check in commented code like this.  Prefer to formulate a plan for clis to import live and cfg, then refactor things appropriately (presumably deleting this).

FWIW, I closed https://github.com/kubernetes-sigs/kustomize/issues/2677 because we defined a sequence that works:
https://github.com/kubernetes-sigs/kustomize/tree/master/releasing#release-sequence.  
Is that order the thing that's hard?  It's annoying, but we're still on the hook to release 5 modules in a full kustomize release, unless we merge some of them.

**Comment by monopole** [comment]
Meh, let's delete and not block on a plan right now.  Still some questions to answer.

**Comment by mortent** [comment]
@monopole Updated the PR to remove the file instead of commenting it out.

**Pull request merged**
