### PR TITLE
variant link update

### PR DESCRIPTION
**Pull request by kundan2707**
updated link for variant in https://github.com/kubernetes-sigs/kustomize/blob/master/examples/breakfast.md

### CODE REVIEW

**Comment by kundan2707** [comment]
FIxes: #5224

**Review by Aisuko — APPROVED** [review]
Approve

**Review by FrenchBen — APPROVED** [review]
LGTM

**Comment by Aisuko** [comment]
cc @koba1t can we get permission to merge these useful PRs?

**Comment by kundan2707** [comment]
@koba1t  OK i will update link at every place

**Comment by natasha41575** [comment]
@kundan2707 do you plan to update this PR?

**Comment by kundan2707** [comment]
@natasha41575  yes i will update at every place

**Comment by kundan2707** [comment]
@natasha41575 i have updated it at every place. Can you PTAL?

**Comment by koba1t** [comment]
Thanks @kundan2707 

But it looks like the below additional lines are using this link. Can you fix that left?
https://github.com/search?q=repo%3Akubernetes-sigs%2Fkustomize+%22%5Bvariant%5D%3A+..%2F%22&type=code

**Comment by kundan2707** [comment]
@koba1t  yes i will fix in additional line too

**Pull request closed without merging**
