### PR TITLE
Replace k8s.gcr.io references with registry.k8s.io

### PR DESCRIPTION
**Pull request by asa3311**
Replace k8s.gcr.io references with registry.k8s.io

### CODE REVIEW

**Review by sftim — COMMENTED** [review]
/ok-to-test

/hold
I wouldn't change `kyaml/openapi/kubernetesapi/v1_21_2/swagger.pb` in this PR.

**Comment by KnVerey** [comment]
/triage accepted
/priority important-soon

Please remove the `kyaml/openapi/kubernetesapi/v1_21_2/swagger.pb` change from the PR, and we'll get this merged.

**Comment by asa3311** [comment]
done

**Pull request merged**
