### PR TITLE
Translated kustomization.yaml into markdown in fields.md. 

### PR DESCRIPTION
**Pull request by cartyc**
Taking a stab at fixing issue #301  .

I tried converting the kustomize.yaml into a markdown file and updated the links in README.md to point to the new file. 

Let me know if I missed anything or any updates need to be made.

### CODE REVIEW

**Comment by Liujingfang1** [comment]
@cartyc Where is the `fields.md` file? If you plan to add one, can you add it like this

| Field       | Type     | Explanation     |
| :------------- | :----------: | -----------: |
|  nameprefix | string  |  Value of this field is prepended to the names of all resources |

Please keep `kustomization.yaml`. Thank you.

**Comment by cartyc** [comment]
@Liujingfang1  Sorry rookie mistake, for some reason it wasn't in the commit I pushed. I'll push it up for review.

**Comment by cartyc** [comment]
I had deleted the kustomize.yaml file as it looked like there was a desire to have it deleted as per pull #464 but I will readd it.

**Comment by monopole** [comment]
will take a look, pls be patient

**Comment by cartyc** [comment]
Thanks @monopole

**Comment by pwittrock** [comment]
@cartyc WDYT of https://github.com/kubernetes/kubectl/pull/647

**Comment by cartyc** [comment]
@pwittrock I can take a look after lunch. What needs to be done?

**Comment by cartyc** [comment]
@pwittrock  just took a look. I can take a crack at kubernetes/kubectl#647 . What is left to be done?

**Comment by monopole** [comment]
Thanks for doing this!

**Comment by cartyc** [comment]
You're welcome @monopole, it was great to be able to help a little. Thanks for the merge :)

**Pull request merged**
