### PR TITLE
Pulling goos and goarch from runtime

### PR DESCRIPTION
**Pull request by mrbrownt**
Pulls the goos and goarch from runtime for version command

### CODE REVIEW

**Comment by monopole** [comment]
Thanks @mrbrownt , can you do the CLA thing referenced above please?

**Comment by mrbrownt** [comment]
I signed up following the link to the linuxfoundation page, verified email but I haven't seen an email about the contributor agreement. Is there something I need to do to trigger that?

**Comment by monopole** [comment]
Per the above message, the usual problem is some mismatch between verification email address and github email settings.  Beyond that, try the CNCF helpdesk: helpdesk@rt.linuxfoundation.org

**Comment by monopole** [comment]
This [PR thread](https://github.com/kubernetes-sigs/kustomize/pull/786) _suggests_ that doing a force push might get the bot to re-evaluate the status on the PR.  Assuming your email settings are correct.

**Comment by mrbrownt** [comment]
I signed the CLA

**Pull request merged**
