### PR TITLE
Use portable method to emulate 'readlink -f' behavior

### PR DESCRIPTION
**Pull request by simster7**
`readlink -f` is [not supported on macOS](https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac), so the `install_kustomize.sh` is broken when run there:

```
$ ./install_kustomize.sh 3.8.8
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

This solution emulates `readlink -f` behavior in a portable way.

Signed-off-by: Simon Behar <simbeh7@gmail.com>

### CODE REVIEW

**Comment by simster7** [comment]
I signed the CLA

**Comment by monopole** [comment]
Nice, it works, thanks!
/ok-to-test
/lgtm

**Review by monopole — COMMENTED** [review]
/lgtm

**Comment by simster7** [comment]
Thanks @monopole!

I may be wrong, but it seems like I need an `/approve` from you to get this merged. Let me know if I misunderstood the process.

/assign @monopole

**Pull request merged**
