### PR TITLE
json-patch upgrade to v4.11.0

### PR DESCRIPTION
**Pull request by pacoxu**
refer to kubernetes/kubernetes#102467

k/k has upgraded it to v4.11.0.

kyaml/kio/byteio_writer.go change is after I run `hack/kyaml-pre-commit.sh`. I think it is valid.

ALLOW_MODULE_SPAN

### CODE REVIEW

**Comment by natasha41575** [comment]
@pacoxu you can run `make prow-presubmit-check` locally to run the test here, looks like something is missing a go.sum entry

**Comment by pacoxu** [comment]
@natasha41575 Updated,

Thanks./

**Comment by monopole** [comment]
Please squash the commits.

**Comment by monopole** [comment]
/test 
kustomize-presubmit-master

**Comment by pacoxu** [comment]
> Please the commits.

squashed @monopole

**Pull request merged**
