### PR TITLE
Add support for extra fieldspecs in configurations for Labels

### PR DESCRIPTION
**Pull request by yutaroyamanaka**
worked on #4816 

I added the support for `Labels` so that users can specify extra `fieldspecs` as well as `commonLabels`.

Here is the example kustomization.yaml.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- pairs:
    someName: someValue
resources:
  # resources.yaml contains a Gorilla and a AnimalPark
  - resources.yaml
configurations:
- labels.yaml
```

resources.yaml

```yaml
apiVersion: animal/v1
kind: Gorilla
metadata:
  name: gg
---
apiVersion: animal/v1
kind: AnimalPark
metadata:
  name: ap
spec:
  gorillaRef:
    name: gg
    kind: Gorilla
    apiVersion: animal/v1
```

labels.yaml

```yaml
labels:
  - path: spec/gorillaRef/metadata/labels
    kind: AnimalPark
    create: true
```

The output of `kustomize build` is as follows

```yaml
apiVersion: animal/v1
kind: AnimalPark
metadata:
  labels:
    someName: someValue
  name: ap
spec:
  gorillaRef:
    apiVersion: animal/v1
    kind: Gorilla
    metadata:
      labels:
        someName: someValue
    name: gg
  template:
    name: template
```

Also, I added an example about this support in `examples/transformerconfigs/README.md`
I'm not very sure where I can add the test case for this support.
I would be grateful if we can discuss this.

### CODE REVIEW

**Comment by KnVerey** [comment]
/triage accepted
/kind feature
/priority backlog

Thanks for the PR! Please add some tests for this new feature. For example, `api/internal/plugins/builtinconfig/transformerconfig_test.go` has `TestMerge` that could be enhanced to cover the labels merge, and `api/krusty/customconfig_test.go` would be a good place for an integration test.

**Comment by yutaroyamanaka** [comment]
@KnVerey Thanks you for providing that information.

- added a unit test to `TestMerge` in `api/internal/plugins/builtinconfig/transformerconfig_test.go`
- added an integration test called `TestCustomConfigLabelsMerge` in `api/krusty/customconfig_test.go`
- fix a typo in `TestMerge` < https://github.com/kubernetes-sigs/kustomize/blob/master/api/internal/plugins/builtinconfig/transformerconfig_test.go#L137

**Comment by koba1t** [comment]
@yutaroyamanaka 
Thanks for your contribution!
Katrina is still very busy. I'll check your PR instead.

**Comment by koba1t** [comment]
/lgtm
Please wait for the review by the maintainers.

/cc @natasha41575 @annasong20

**Comment by stormqueen1990** [comment]
Superseded by #5556

/close

**Pull request closed without merging**
