### PR TITLE
chore: Update to Go v1.21

### PR DESCRIPTION
**Pull request by karlkfi**
Includes:
- go mod tidy (all modules)
- go work sync
- Fixed plugin generation for Go 1.21
- Updated linting for Go 1.21
- Fixed minecraft example for Helm v3 pull download path
- Update dev docs to mention Go 1.21
- Regenerate plugins with Go 1.21

Depends on https://github.com/kubernetes/test-infra/pull/31974

Blocking https://github.com/kubernetes-sigs/kustomize/pull/5535

### CODE REVIEW

**Comment by koba1t** [comment]
> go work sync

In my experience, that is better to run `./hack/doGoMod.sh tidy` after running the `go work sync` command.

**Comment by karlkfi** [comment]
> > go work sync
> 
> In my experience, that is better to run `./hack/doGoMod.sh tidy` after running the `go work sync` command.

`./hack/doGoMod.sh tidy` and `hack/for-each-module.sh` are basically the same thing, except for-each-module skips `site/` modules. But I ran both just in case.

**Comment by karlkfi** [comment]
Rebased and fixed plugin generation. `make prow-presubmit-check` and `make verify-kustomize-repo` now pass for me locally.

In order for the prow test to pass in prow, the prow config needs to be updated to support Go 1.21: https://github.com/kubernetes/test-infra/pull/31974

**Comment by koba1t** [comment]
Hi @karlkfi 
I approved the PR that upgrades the go version in CI.
So, Could you rebase master this PR to merge?

**Comment by karlkfi** [comment]
Rebased and passed all test!

**Comment by karlkfi** [comment]
(Rebasing these is a pain, cause it conflicts with every go.mod and go.sum change.)

**Comment by koba1t** [comment]
Thanks! I'll review.
/assign @koba1t

**Review by ncapps — COMMENTED** [review]
/lgtm

**Pull request merged**
