### PR TITLE
Add Support for Paginated Pull Request Responses to Multi-Module Check

### PR DESCRIPTION
**Pull request by runewake2**
Updates the go script to handle file lists spanning multiple GitHub api pages. This allows the script to support Pull Requests which include more than 100 files.

See issue #2774

### CODE REVIEW

**Comment by Shell32-Natsu** [comment]
Sometimes we have to update multiple modules in a single PR. For example, if the API definition is changed in kyaml then the functions in api module must be updated at the same time if the kyaml module is not pointed to a fix version in api module. According to #2774, we should be able to add a command/flag in the PR description to disable the check.

**Comment by mortent** [comment]
So I don't think there is any problem to have PRs to span multiple modules as long as each of the commits in the PR doesn't span multiple modules.

**Comment by runewake2** [comment]
@mortent Can we move the conversation about this to the issue at #2774? This may change the scope of this work. We can delay this PR until that is addressed.

**Comment by monopole** [comment]
@runewake2 for this PR please just make the change to the go, so we can get that in.

**Comment by monopole** [comment]
i.e. stash the makefile change for the moment

**Comment by runewake2** [comment]
I've removed Makefile changes from this PR and edited the PR comment and title to be more accurate to this new state. Donny's comment has not been addressed.

**Review by monopole — COMMENTED** [review]
/lgtm

**Pull request merged**
