### PR TITLE
add test for issues raised in #2734

### PR DESCRIPTION
**Pull request by hornpolish**
hello @monopole;  this tests the three things that we found to have regressed with the kyaml merges.  the test currently fails, because we hope you'll agree the behaviour w.r.t. {} needs to be reverted.  waiting for community comments on "null"

thanks!

### CODE REVIEW

**Comment by hornpolish** [comment]
sorry again for submitting a test that "fails".  

its not clear what to do when that is the point - to show a regression.

**Comment by hornpolish** [comment]
@monopole -- i did this one before https://github.com/kubernetes-sigs/kustomize/pull/2777 ; 

if you prefer i can rework it so:

1. it documents current state (ie passes, but shouldnt)
2. lives in plugin/builtin/patchstrategicmergetransformer/PSMT_test.go   (rather that api/filters/patchstrategicmerge...

**Comment by monopole** [comment]
/lgtm

Thanks @hornpolish 

Seems we've agreed in #2734 by lazy consensus to retain the `{}` but drop 
```
creationTimeStamp null
```
We can rejigger the comments as to the desirability of this behavior when the fix for retaining `{}` goes in.


Regardless, this test does a great job establishing the regression.

**Pull request merged**
