### PR TITLE
tooling performance improvements, better structure

### PR DESCRIPTION
**Pull request by damienr74**
Refactored the crawler implementation to make the whole thing more
testable. Added a document interface to make the crawler generic.
This will be useful for collecting plugins, and other documents.

This also includes the comment explaining the search splitter you
mentioned a while ago.

This adds a fair amount of testing to the crawler, which I feel better about.
 internal/tools/doc/kustomize_util.go is just a copy of the functions in pkg/types
and it's only copied to remove the panic. If you prefer, I can modify the actual code
to bubble up the error if you prefer.

The next commit will have the implementation specific stuff and will likely include more
redis code.

Also, I can split this up into smaller chunks if you like, but this is a functional unit.

### CODE REVIEW

**Comment by richardmarshall** [comment]
Hey @damienr74, seen the PRs over the last two weeks related to the `internal/tools` code and have been able to put together the general idea of what this is all doing. That said is there a public document somewhere that describes what the high level goals / plans are for this project?

Tried searching for references to this but wasn't able to find anything obvious.

**Comment by monopole** [comment]
we're prototyping the idea of a config exploration/indexing service - what it might look like, how to seed it etc.  not intended for GA, so light on code rev at this point

**Comment by damienr74** [comment]
Hi @richardmarshall,

The closest thing would probably be what's included in the [README.md](https://github.com/kubernetes-sigs/kustomize/blob/master/internal/tools/README.md) and the [ROADMAP.md](https://github.com/kubernetes-sigs/kustomize/blob/master/internal/tools/ROADMAP.md)

There is still this PR that is not yet merged in the repo, so the running instructions will be incomplete. Also it seems like I did not set up the markdown image links properly, but they are in the `internal/tools/pictures` directory if you want to have a look.

**Comment by richardmarshall** [comment]
@monopole @damienr74 Thanks for the context.

**Pull request merged**
