### PR TITLE
run openapi tests with other krusty tests

### PR DESCRIPTION
**Pull request by natasha41575**
We don't need to run them separately

### CODE REVIEW

**Comment by natasha41575** [comment]
/cc @KnVerey 

I want to run the test suite a few times before merging this

**Comment by natasha41575** [comment]
The test seem fine. I think we can safely merge this. @KnVerey could you please review this whenever you get the chance?

/hold cancel

**Comment by KnVerey** [comment]
/lgtm
/approve

In case we forget and look back on this PR in the future: We now think we were misinterpreting a sequencing issue we've since fixed as a parallelism issue that should be impossible because separate packages are tested with separate test binaries. If the problem recurs, rather than revert this, we should investigate it as likely caused by a test in the same package corrupting the global state. It's also worth noting in such investigations that we do not currently run any tests within a suite in parallel (which would require `t.Parallel` calls).

**Pull request merged**
