### PR TITLE
fix `TestRemoteLoad_LocalProtocol`

### PR DESCRIPTION
**Pull request by natasha41575**
Testing out if this fixes the failure on master 

Using the workaround described in https://bugs.launchpad.net/ubuntu/+source/git/+bug/1993586

### CODE REVIEW

**Comment by koba1t** [comment]
I think this workaround solves the test failure on the master.
And, I checked to fail tests for add `git config --global protocol.file.allow user`.

/lgtm

**Comment by koba1t** [comment]
Oh... Was that bad to type to `/lgtm`?
If you wanted to do other checks before merging the master, That apologizes from me.

**Comment by natasha41575** [comment]
> If you wanted to do other checks before merging the master, That apologizes from me.

That's okay! Thanks for the LGTM. This will at least unblock other PRs for now. I already let the other maintainers know about this PR, so they can take a look if they'd like.

**Pull request merged**
