### PR TITLE
unify processing of JSON6902 patches for both json and yaml format

### LINKED ISSUE #368: YAML-formatted JSON6902 patches are added twice
overlay `kustomization.yaml`:
```patchesJson6902:
- path: add_args.yaml
  target:
    group: apps
    kind: Deployment
    name: external-dns
    version: v1
```

overlay `add_args.yaml`:
```- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --domain-filter=sandbox-kubeadm.us-east-1.tktm.io
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --txt-owner-id=sandbox-kubeadm
```

output:
```
      - args:
        ...
        - --domain-filter=sandbox-kubeadm.us-east-1.tktm.io
        - --txt-owner-id=sandbox-kubeadm
        - --domain-filter=sandbox-kubeadm.us-east-1.tktm.io
        - --txt-owner-id=sandbox-kubeadm
```

### PR DESCRIPTION
**Pull request by schweikert**
Previous to this change, a different library was used for json-formatted patches and for yaml-formatted patches.

This gets rid of the yaml-specific transformer and just transforms the yaml-formatted patches to json first.

fixes #368

### CODE REVIEW

**Comment by schweikert** [comment]
I don't know why the travis-ci is not testing this anymore. I did a rebase and force push.

**Comment by schweikert** [comment]
Maybe I close this one and recreate a pull request?

**Comment by Liujingfang1** [comment]
Yes, please try it :)

**Comment by schweikert** [comment]
recreated as #422

**Pull request closed without merging**
