### PR TITLE
Iterate over fieldspecs for name tranformations (fixes #1228)

### LINKED ISSUE #1228: Regression in namePrefix configuration in 2.1.0
In 2.1.0 there seems to be a regression in how namePrefix configuration works.  Before, it was possible to specify several fieldspecs for the same kind (e.g. `Deployment`) and the prefix would be applied at all the locations specified by the fieldspecs.  Now it appears that only the first one is applied.  Here is a minimal example:

- example/config.yaml
```yaml
namePrefix:
  - kind: Deployment
    path: spec/template/spec/containers/name
```

- example/deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: main
        image: myapp
```

- example/kustomization.yaml
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - deployment.yaml
configurations:
  - config.yaml
namePrefix: test-
```

Using kustomize v0.0.0-20190521031729-72f565d55d2c
```
$ kustomize build example
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  template:
    spec:
      containers:
      - image: myapp
        name: test-main
```

Using kustomize v2.1.0 (kustomize@v0.0.0-20190618214009-af67c893d87c)
```
$ kustomize build example
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - image: myapp
        name: test-main
```

The prefix is no longer applied to the metadata/name of the deployment.

If I add a rule for prefixing metadata/name explicitly, then the other one is ignored:

- example/config.yaml
```
namePrefix:
  - kind: Deployment
    path: metadata/name
  - kind: Deployment
    path: spec/template/spec/containers/name
```

Using kustomize v2.1.0 (kustomize@v0.0.0-20190618214009-af67c893d87c)
```
$ kustomize build example
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  template:
    spec:
      containers:
      - image: myapp
        name: main
```

### PR DESCRIPTION
**Pull request by arnodel**
See #1228 for details of the issue.

### CODE REVIEW

**Comment by monopole** [comment]
Thanks for jumping on this!

It looks good, but to keep it fixed please add a test that recreates the regression you noted.

Want to include this in 2.1.1, which goes out next week!

**Comment by arnodel** [comment]
Thanks, will do ASAP!

**Comment by arnodel** [comment]
- I had a slight bit of trouble figuring out how to run the tests (hence the failures!).
- I don't know if it's ok to add the new test case to the same test the way I did - I'll change it otherwise.

**Comment by monopole** [comment]
normally would put this in a new test, e.g.

func TestPrefixSuffixTransformerSomeOtherName(t *testing.T) {
}

but this is fine.

/lgtm

**Pull request merged**
