### PR TITLE
empty list or map item return error

### PR DESCRIPTION
**Pull request by nimohunter**
hey, i'm new to this repo and trying to solve this issue  #1182 , but i don't know Is this a good way to add check code in k8sdeps/kunstruct/factory.go.  If the handling here is not appropriate, please tell me how to modify it :)

### CODE REVIEW

**Comment by monopole** [comment]
the tests are failing.
to run locally, execute
```
./travis/pre-commit.sh
```
from your repo directory

**Comment by nimohunter** [comment]
@monopole thanks for your help! and i remove the nil value check in map, just keep nil value check in list, and pass the pre-commit.sh now.

**Comment by monopole** [comment]
I appreciate and acknowledge that the new  resource/factory_test.go fails if the call to checkListItemNil in k8sdeps/kunstruct/factory_test.go is commented out.

Wouldn't it be better if there were also (or instead) another test in  TestSliceFromBytes in k8sdeps/kunstruct/factory_test.go that would fail without that call?

I.e. can we demo the bug in the k8sdeps package, and that the new code path fixes the bug there - since that's where the new code is?

**Comment by nimohunter** [comment]
@monopole thanks! so i move the test case from resource/factory_test.go to kunstruct/factory_test.go, but i have no sure about the checkListItemNil method, Is it a reasonable?  Is it can to fix this bug and will not bring other problem?

**Comment by monopole** [comment]
/lgtm
/approve
thanks!

**Pull request merged**
