### PR TITLE
Remove site and docs folder

### PR DESCRIPTION
**Pull request by rob8714**
Removes the site and docs folder to tackle https://github.com/kubernetes-sigs/kustomize/issues/3915

Pages that did not have redirects:

docs/authoring.md - partially migrated in https://github.com/kubernetes-sigs/cli-experimental/pull/244
docs/guides/cmd - migrated in https://github.com/kubernetes-sigs/cli-experimental/pull/244
docs/inventory_object.md - page was marked as deprecated
site/content/en/blog/releases/v* - content already present in cli-experimental
content/en/_index.md, content/zh/_index.md, content/en/search*.md, content/zn/search* - don't think these would need to be tackled

### CODE REVIEW

**Comment by KnVerey** [comment]
I agree with your assessment of the content. 

Since this is impossible to view on Github, to sanity check it, I pulled the branch locally and confirmed that only the expected directories are affected: `git diff --name-only HEAD~2  -- ':!docs/' ':!site/'`

/lgtm
/ok-to-test
/hold on merging https://github.com/kubernetes-sigs/cli-experimental/pull/244 and deactivating the site publishing these files

**Comment by rob8714** [comment]
Noticed that some images in README were going to break, copied over the base.jpg and overlay.jpg into a new `images` folder and additionally fixed overlay.jpg to remove the reference to bases (https://github.com/kubernetes-sigs/kustomize/issues/1555)

**Comment by KnVerey** [comment]
Great catch on those images! I just took the site down. Assuming nothing unexpected comes up as a result, I'll merge this tomorrow morning.

**Comment by KnVerey** [comment]
#4500 reported a few places we missed on kustomize.io and the readme. I opened PRs and unfortunately caused a merge conflict for this PR in the process. Can you rebase please? (sorry)

**Comment by KnVerey** [comment]
Fixes https://github.com/kubernetes-sigs/kustomize/issues/3915

**Comment by rob8714** [comment]
Rebase done. Should also fix https://github.com/kubernetes-sigs/kustomize/issues/1555

**Comment by KnVerey** [comment]
I think something went wrong with the rebase, as I'm now seeing 14 commits in the history here.

**Comment by rob8714** [comment]
Hmm I checked it again and from what I see changes that will be applied are those from this PR only:

image

If it's easier I can redo the changes in a new PR

**Comment by KnVerey** [comment]
Yeah the last four are still yours, but this PR is now showing a bunch of other already merged commits before it: https://github.com/kubernetes-sigs/kustomize/pull/4491/commits. I'm not sure why this is happening. I'd suggest `git rebase -i master` and make sure to remove any commits showing that aren't in this PR. Remaking the PR by checking a new branch off master and cherry-picking would also work--whatever is easiest for you.

**Comment by rob8714** [comment]
Went with a new PR - https://github.com/kubernetes-sigs/kustomize/pull/4504

**Pull request closed without merging**
