### PR TITLE
Remove starlark support

### PR DESCRIPTION
**Pull request by dims**
Helps drop starlark from kubernetes dependencies, also found an issue here https://github.com/kubernetes-sigs/kustomize/issues/4349 as well

```
❯ go mod graph | grep go.starlark.net | sort
go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca github.com/chzyer/logex@v1.1.10
go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca github.com/chzyer/readline@v0.0.0-20180603132655-2972be24d48e
go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca github.com/chzyer/test@v0.0.0-20180213035817-a1ea475d72b1
go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca github.com/google/go-cmp@v0.5.1
go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca golang.org/x/sys@v0.0.0-20220715151400-c0bba94af5f8
go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca golang.org/x/term@v0.0.0-20220526004731-065cf7ba2467
go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1
go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca google.golang.org/protobuf@v1.25.0
k8s.io/cli-runtime go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca
k8s.io/cli-runtime@v0.0.0 go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca
k8s.io/kubectl go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca
k8s.io/kubectl@v0.0.0 go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca
k8s.io/kubernetes go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca
k8s.io/sample-cli-plugin go.starlark.net@v0.0.0-20230525235612-a134d8f9ddca
sigs.k8s.io/kustomize/api@v0.17.2 go.starlark.net@v0.0.0-20200306205701-8dd3e2ee1dd5
sigs.k8s.io/kustomize/kustomize/v5@v5.4.2 go.starlark.net@v0.0.0-20200306205701-8dd3e2ee1dd5
sigs.k8s.io/kustomize/kyaml@v0.17.1 go.starlark.net@v0.0.0-20200306205701-8dd3e2ee1dd5
```

### CODE REVIEW

**Review by stormqueen1990 — COMMENTED** [review]
/lgtm

**Comment by koba1t** [comment]
@dims 
Thanks for sending the cleanup PR for the deprecated feature!

However, I think it would be better to remove the three currently deprecated alpha plugins at the same time.
Unless you have a reason to rush the removal of this feature, it may take some time to make progress.
https://kubectl.docs.kubernetes.io/guides/extending_kustomize/#plugin-feature-status

**Comment by koba1t** [comment]
### The results of my investigation

According to the Kustomize plugin proposal, we can only remove the legacy 'exec' and 'Go' plugins after we move to the beta phase.
Therefore, we can't delete the above two legacy plugins now.
https://github.com/kubernetes/enhancements/blob/61b21e5105e5fda4d6c53821ff82dd39a1a98f07/keps/sig-cli/2953-kustomize-plugin-graduation/README.md#L587

The proposal says that the 'starlark plugin' will be removed after the transition to beta. However, considering the lack of response to the following issue, we think it is safe to remove it now to cleanup dependencies。
https://github.com/kubernetes-sigs/kustomize/issues/4349

/lgtm
/approve

**Pull request merged**
