### PR TITLE
add DisableNameSuffixHash parameter to edit Secret & ConfigMap

### LINKED ISSUE #2868: add disableNameSuffixHash as optional parameter to kustomize edit set secret command
We can specify disableNameSuffixHash parameter in kustomization.yaml but we can not specify it via cli. It would be nice to pass disableNameSuffixHash parameter from cli to prevent adding random generated suffix to secrets/configmaps.

I would like to create pr for that feature if it sounds reasonable.

### PR DESCRIPTION
**Pull request by mstrYoda**
fix #2868

### CODE REVIEW

**Comment by monopole** [comment]
/ok-to-test
/lgtm

thanks!

**Comment by mstrYoda** [comment]
> /ok-to-test
> /lgtm
> 
> thanks!

Hi @monopole how/when can me merge this? Is it need to approved label additionally?

**Pull request merged**
