### PR TITLE
added tests for merge key tuple behavior

### PR DESCRIPTION
**Pull request by natasha41575**
reference to #3111 

These test cases should be fixed by #3159

### CODE REVIEW

**Comment by monopole** [comment]
/lgtm

thanks, this helps a great deal

**Comment by phanimarupaka** [comment]
@natasha41575 As discussed offline, It would be better to add tests for Merge3 as well in this PR to understand the behavior.

**Comment by monopole** [comment]
/hold

@phanimarupaka  Agreed, please add tests for merge3 here as well.

You're paying down a tech debt you didn't create, but that's part of the job.
A test-only PR in front of a major change is normal to establish more coverage.

@phanimarupaka If you can list some suggested scenarios here or offline it would help.

**Comment by phanimarupaka** [comment]
@monopole Sure. Will do.

**Comment by monopole** [comment]
/lgtm
More tests coming in #3183

**Pull request merged**
