### PR TITLE
fix binary install script

### LINKED ISSUE #3154: binary install script not working for some releases
**Describe the bug**

install kustomize script does not appear to work for latest version (v3.8.6) when specified or when no version string is specified 

**Files that can reproduce the issue**

[install_kustomize.sh](https://github.com/kubernetes-sigs/kustomize/blob/6a9e75ee0d558683b989fe42e7edc02e84c990a9/hack/install_kustomize.sh)

**Expected/Actual output**

- using script without specifying a version
```sh
$ curl -sfL https://raw.githubusercontent.com/\
> kubernetes-sigs/kustomize/master/hack/install_kustomize.sh  | bash
Error: kustomize binary with the version  does not exist!
```

- using script specifying the latest (3.8.6) version
```sh
$ bash <(curl -sfL https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh) 3.8.6
Error: kustomize binary with the version 3.8.6 does not exist!
```

- using script with a previous version (3.8.5)
```sh
$ bash <(curl -sfL https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh) 3.8.5
{Version:kustomize/v3.8.5 GitCommit:4052cd4fd8c76a17b5f64e32509f3fba9713fe75 BuildDate:2020-10-08T02:45:59Z GoOs:linux GoArch:amd64}
kustomize installed to current directory.
```

**Kustomize version**

N/A

**Platform**

Linux

**Additional context**

N/A

### PR DESCRIPTION
**Pull request by radTuti**
close #3154

### CODE REVIEW

**Comment by radTuti** [comment]
I signed it

**Review by shashanktomar — APPROVED** [review]

**Comment by Shell32-Natsu** [comment]
Will merge this PR at first to fix the urgent issue. I will create another issue to address ARM builds.

**Comment by Shell32-Natsu** [comment]
Thanks a lot for the fix

**Pull request merged**
