### PR TITLE
upgrade json-patch to v5.5.0

### PR DESCRIPTION
**Pull request by pacoxu**
refer to https://github.com/kubernetes/kubernetes/pull/102467

### CODE REVIEW

**Comment by liggitt** [comment]
/hold

let's make sure kubernetes is ready to move to jsonpatch v5 before merging this (there's a compatibility break between v4 and v5 with patch paths lacking a / prefix

**Comment by pacoxu** [comment]
Got it. I will try to learn the context.
Thanks.

**Comment by pacoxu** [comment]
Link the issue here https://github.com/evanphx/json-patch/issues/86.

**Comment by liggitt** [comment]
Looks like json-patch also released v4.10.0 to make the fix available in the v4 stream. That seems like it might be a better version to switch to (let's verify in https://github.com/kubernetes/kubernetes/pull/102467#issuecomment-853032039 first)

**Comment by monopole** [comment]
ack.

**Comment by monopole** [comment]
@KnVerey  
just an fyi.

**Comment by pacoxu** [comment]
As #102467, we upgrade to v4.11.0 because of v5.5.0 has break changes: 
- JSON patch implemented by https://github.com/evanphx/json-patch now conforms to RFC6902 replacement semantics and does not accept "replace" patch operations if the specified path does not exist.

**Pull request closed without merging**
