### PR TITLE
Revert "Skip adding nameprefix to namespace"

### PR DESCRIPTION
**Pull request by Liujingfang1**
Reverts kubernetes-sigs/kustomize#488

### CODE REVIEW

**Comment by chauffer** [comment]
Why was this reverted?

**Comment by sknigh** [comment]
@Liujingfang1 I would like to know why this was reverted as well. Is there a way to define a namespace resource, and use a namespace+nameprefix in kustomization.yaml?

**Comment by mengqiy** [comment]
IIRC the change in #488 actually is not backward compatible. Be I can't recall the details.
I guess @Liujingfang1 should know.

**Pull request merged**
