### PR TITLE
docs: update patchMultipleObject example to filter with labelSelector

### PR DESCRIPTION
**Pull request by johnzheng1975**

### CODE REVIEW

**Comment by johnzheng1975** [comment]
The purpose for this PR is:
adding test "labelSelector: key=value". 
There is no similar examples. I think it is valuable to add some samples here.

You know, the kustomize has no useful logic like "if else", this labelSelector is very useful to implement this logic.

**Comment by johnzheng1975** [comment]
BTW, I already test pass. Pls review, thanks.

**Comment by koba1t** [comment]
Hi @ncapps 
Could you review this PR?

**Comment by koba1t** [comment]
/retitle docs: update patchMultipleObject example to filter with labelSelector

**Comment by koba1t** [comment]
Thanks @johnzheng1975 

/lgtm
/approve

**Pull request merged**
