### PR TITLE
LOGO TRY

### PR DESCRIPTION
**Pull request by antoniasymeonidou**

### CODE REVIEW

**Comment by pwittrock** [comment]
Thanks for this! Love the idea of a logo.

Probably want to discuss amongst the community what we might want the logo to look like.

**Comment by antoniasymeonidou** [comment]
Hello Phillip,

When you discuss with your team i can make for you the perfect fit logo for your coding. This is my job so if you want something spesific i can give you a very low price for your logo.

Thank you in advance

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by antoniasymeonidou** [comment]
Hello Phillip,

When you discuss with your team i can make for you the perfect fit logo for your coding. This is my job so if you want something spesific i can give you a very low price for your logo.

Thank you in advance


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by pwittrock** [comment]
Hi @antoniasymeonidou.  While we appreciate the offer, we aren't looking to pay for a logo right now.

**Pull request closed without merging**
