### PR TITLE
When using CRDs, register scheme so that strategic patches work

### PR DESCRIPTION
**Pull request by dmayle**
Strategic Merge patches only work for types that are known to the client.  This change hooks into the CRD loader and registers any new CRDs so that strategic merge patches will work properly.

### CODE REVIEW

**Comment by monopole** [comment]
thanks for doing this.  Can you please add a test?
Preferably a test that shows what happens if this code isn't in place,
and then this code makes the test pass.
So something that fails because of a lack of registration.

**Comment by dmayle** [comment]
@monopole any chance you could point me towards an example test? and/or any docs about testing for kustomize?  I didn't see any existing 'golden' files in the repo, so it's not clear to me how to write one.

**Comment by pwittrock** [comment]
@dmayle updating https://github.com/kubernetes-sigs/kustomize/blob/master/api/internal/accumulator/loadconfigfromcrds_test.go would probably be sufficient

**Comment by tamalsaha** [comment]
This does not sound right. For strategic patch to work for CRDs, it needs the structural schema I believe. 

cc: @lavalamp @sttts

**Comment by sttts** [comment]
Strategic merge patch does not work for CRDs at all (and won't in the future; strategic merge patch is going to be replaced with server side apply). That has nothing to do with the client.

**Comment by lavalamp** [comment]
JSON patch and JSON merge-patch work for CRDs.

I recommend trying SSA, that also works for CRDs.

Once SSA goes GA, we will most likely deprecate SMP for all resources.

**Comment by pwittrock** [comment]
@sttts @lavalamp IIUC, this is for merging 2 resource configuration files on the client side (e.g. kustomize patches).  The PR would need to register the OpenAPI schema for the type defined by the CRD, and then SMP would work on the client-side for CRD based types.  SSA won't work for merging 2 configuration files on the client-side.

**Comment by sttts** [comment]
@pwittrock that could indeed work. list-types and map-types exist for CRDs and we publish them. They could drive SMP client-side.

**Comment by lavalamp** [comment]
Where is SMP used client side? We should figure out what it would take to switch to SSA code (which could in theory also be run client side).

**Comment by pwittrock** [comment]
@lavalamp SSA probably won't be sufficient.  We are moving off the SMP code and onto an implementation built on the go yaml v3 libraries because:

- we need to retain yaml data such as comments and structure when merging resources
- we need to remove the dependency on staging so the kustomize libraries can be updated in kubectl

I'm also not sure the SSA model is the right fit -- e.g. it assumes a single owner per-field, whereas the kustomize patch model does not, and is designed to support overrides.

**Comment by lavalamp** [comment]
If you just need merging, you can ignore the managed fields and use SSA code.

If you are merging with SMP I want to find a way to help you not do that.

**Comment by pwittrock** [comment]
SG, what's the best way to move forward?

**Comment by lavalamp** [comment]
I don't know-- where are you using SMP client side? Do you have access to a schema at that place?

@apelisse fyi

**Comment by pwittrock** [comment]
Lets move this discussion off this PR.

**Comment by pwittrock** [comment]
Created #2290 for SSA patch discussion

**Comment by pwittrock** [comment]
We are working towards solving this by rebasing on kyaml, which will support more schema options.

**Comment by lukadante** [comment]
@pwittrock is there a place where we can track progress on the issue?

**Comment by pwittrock** [comment]
#2339

**Comment by pwittrock** [comment]
There have been 1/2 dozen PRs for this already.  @mortent has been doing a great job driving this forward.

**Comment by lukadante** [comment]
> @lukadante #2339

thank you!

**Pull request closed without merging**
