### PR TITLE
kyaml: Enable Go linters (lll, stylecheck, unparam, whitespace)

### PR DESCRIPTION
**Pull request by artmello**
Part of #1772

### CODE REVIEW

**Comment by hypnoglow** [comment]
@artmello There are lint issues in CI. Maybe the assumption that linters you enabled don't produce issues was made based on running golangci-lint of a different version. Can you please check that you run golangci-lint v1.19.1 locally to reveal the issues?

**Comment by artmello** [comment]
@hypnoglow Indeed there was an issue on my local setup (both wrong version and a mistake on how I called linters locally). I pushed fixes to the issues found.I tried to keep fixes related with a specific linter inside a single commit, but this is not following the recommendation of one PR for each enabled linter (as described on initial issue). If necessary, I can split it on multiple PRs.

**Comment by pwittrock** [comment]
Almost there!

**Pull request merged**
