### PR TITLE
Simplify git cloner logic

### PR DESCRIPTION
**Pull request by yujunz**
Related to #2072

### CODE REVIEW

**Comment by yujunz** [comment]
Refer to https://stackoverflow.com/questions/21833870/how-do-i-shallow-clone-a-repo-on-a-specific-branch

**Comment by Liujingfang1** [comment]
/lgtm

@yujunz Did you verify the change on #2072

**Comment by monopole** [comment]
yeah, this used to be "clone" then "checkout {branch}" in two steps (pre #857).  thanks

/lgtm

As @Liujingfang1 suggests, please add `Fixes #2072` to the description if that error goes away on your fork.

**Comment by yujunz** [comment]
> @yujunz Did you verify the change on #2072

Yes. I verified it locally.

**Comment by yujunz** [comment]
> As @Liujingfang1 suggests, please add `Fixes #2072` to the description if that error goes away on your fork.

It seems already merged. Will do next time.

Some repository will prevent issues from closing automatically so I didn't add the trigger.

**Pull request merged**
