### PR TITLE
chore(docs): fix grammar error in comment

### PR DESCRIPTION
**Pull request by crenshaw-dev**

### CODE REVIEW

**Comment by charles-chenzz** [comment]
please refer this link
https://www.kubernetes.dev/docs/guide/pull-requests/#trivial-edits

**Comment by crenshaw-dev** [comment]
@charles-chenzz I've read all the comments, and this was the only one with a grammar error. I noticed one function which might benefit from a comment, so I added a comment.

**Comment by koba1t** [comment]
Hi @charles-chenzz 
Could you re-review this PR?

**Review by kundan2707 — COMMENTED** [review]
/lgtm

**Comment by koba1t** [comment]
@crenshaw-dev 

Thanks for your contribute!
I am so sorry it took a long time to review.

/approve

**Pull request merged**
