### PR TITLE
Add support to install kustomize to specified directory

### PR DESCRIPTION
**Pull request by MaXinjian**
Signed-off-by: Ma Xinjian <maxj.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by Shell32-Natsu** [comment]
Is this just a convenient alias for `cd dir && install_kustomize.sh`?

**Comment by MaXinjian** [comment]
> Is this just a convenient alias for `cd dir && install_kustomize.sh`?

Yes.
I find hack/install-kpt.sh support to install to specified dir, it's indeed convinient.

**Review by monopole — APPROVED** [review]
/lgtm

**Pull request merged**
