### PR TITLE
chore: remove unused function

### PR DESCRIPTION
**Pull request by emirot**
Remove unused function forgot from previous PR https://github.com/kubernetes-sigs/kustomize/commit/bcb1a367aa3bbd88fbc047217e27dbf1a66657d5

### CODE REVIEW

**Review by stormqueen1990 — COMMENTED** [review]
Hi @emirot! Thanks for that!

/ok-to-test

**Comment by koba1t** [comment]
Thanks for your contribution, @emirot!!
/approve

**Pull request merged**
