### PR TITLE
Upgrade cobra for better zsh support

### PR DESCRIPTION
**Pull request by sylr**
`kustomize build ...` does not complete file paths on ZSH.

It will with this upgrade.

### CODE REVIEW

**Comment by sylr** [comment]
@natasha41575 could you merge this please ?

**Comment by sylr** [comment]
@natasha41575 ?

**Comment by KnVerey** [comment]
I was initially very wary of all the new dependencies this pulls in, but I see that kubectl has already merged the same upgrade (and indeed already had most of the dependencies in question from other sources before the upgrade): https://github.com/kubernetes/kubernetes/pull/103448.

PR needs rebase before LGTM.

/approve

**Comment by sylr** [comment]
@KnVerey rebased

**Pull request merged**
