### PR TITLE
Fix 3489

### LINKED ISSUE #3489: Kustomize "multiple matches" failure since kustomize/v3.9.2
**Describe the bug**

Kustomize workspace which was working up until kustomize/v3.9.1 now fails **with and without** `kyaml`.

```
$ ~/go/src/sigs.k8s.io/kustomize/kustomize/kustomize build --enable_kyaml=false .
Error: obj '{"apiVersion": "rbac.authorization.k8s.io/v1", "kind": "ClusterRoleBinding", "metadata": {
    "annotations": {"config.kubernetes.io/originalNs": "default"}, "labels": {"app": "external-dns",
      "instance": "public"}, "name": "external-dns-viewer"}, "roleRef": {"apiGroup": "rbac.authorization.k8s.io",
    "kind": "ClusterRole", "name": "external-dns"}, "subjects": [{"kind": "ServiceAccount",
      "name": "external-dns"}]}
' at path 'subjects': multiple matches for ~G_v1_ServiceAccount|default|external-dns:
  [~G_v1_ServiceAccount|kube-system|external-dns
 ~G_v1_ServiceAccount|kube-system|external-dns-private
]
```
```
$ ~/go/src/sigs.k8s.io/kustomize/kustomize/kustomize build  .
Error: obj 'apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
  labels:
    app: external-dns
    instance: public
  annotations:
    config.kubernetes.io/originalNs: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
' at path 'subjects': multiple matches for ~G_v1_ServiceAccount|default|external-dns:
  [~G_v1_ServiceAccount|kube-system|external-dns
 ~G_v1_ServiceAccount|kube-system|external-dns-private
]
```

**Files that can reproduce the issue**

https://github.com/sylr/kustomize-crash-reproduction

### PR DESCRIPTION
**Pull request by monopole**
Fixes #3489

For some time,  SameEndingSubarray (formerly private, with no unit test) was treating an empty array and a one entry array as having the same "ending subarray" which was failing to eliminate referral targets that differed by one prefix or suffix in one referral target.  This change fixes that, improving referral target filtering.  This comes up in diamond patterns, where one branch adds a prefix or suffix, and the other branch doesn't.

### CODE REVIEW

**Comment by sylr** [comment]
I'm not capable of doing a code review but can assert that it fixes #3489.

LGTM 👍

**Comment by natasha41575** [comment]
@monopole Do you have a preference if this goes in first or if #3525 goes in first?

**Pull request merged**
