### PR TITLE
Fix typo: kubectl v1.15 -> kubectl v1.14

### PR DESCRIPTION
**Pull request by gosharplite**
Match version number to the version in the link.

### CODE REVIEW

**Comment by Liujingfang1** [comment]
kustomize 2.0.3 is available in kubectl 1.14 and 1.15. Can you add both of them? Thank you

**Comment by gosharplite** [comment]
Yes, I have put both v1.14 and v1.15 into this PR.

I originally thought K8s v1.15 release note should announce it uses kustomize v2.0.3, then I tried `$kubectl kustomize version`, but it doesn't work.

It seems this PR will become the only place a user can get the relationship between `kubectl kustomize` and `kustomize` in a straight forward way.

Is there other work in progress that will let a user find this info easier?

**Comment by gosharplite** [comment]
I have amended my commit with correct email address.
Hopefully the `cncf-cla` flag will be cleared.

**Comment by tonyhsu2019** [comment]
I have also signed the CLA with this account `tonyhsu2019`.
Let's see if this will clear the `cncf-cla`.

**Pull request merged**
