### PR TITLE
add the Chhinese translation of docs list & install

### PR DESCRIPTION
**Pull request by sunny0826**
- Translated docs/README
- Translated docs/INSTALL

### CODE REVIEW

**Comment by Liujingfang1** [comment]
Can you rebase the master and solve the conflicts.

**Comment by sunny0826** [comment]
I updated the docs list and install, and added a description at the end - "The Chinese version of this site may be slightly out of date compared to the English version. Please consult the English version if you experience any problems".

**Comment by Liujingfang1** [comment]
/approve
Looks good to me. Can you squash all the commits? Thank you.

**Comment by sunny0826** [comment]
Do you mean that each Chinese document needs to be added to this "statement"?

**Comment by Liujingfang1** [comment]
@sunny0826  Use `git rebase -i HEAD~[N]` to put all your 9 commits into one commit. You can also take a look at this page https://www.internalpointers.com/post/squash-commits-into-one-git

**Comment by sunny0826** [comment]
I squash all the commits and solve the conflicts.

**Pull request merged**
