### PR TITLE
Remove misleading documentation about config generation

### PR DESCRIPTION
**Pull request by VannTen**
/kind cleanup

Follow-up to #3146, cleaning examples as well.

(Note that this files appeart pretty high in search results when looking for "kustomize configmap generation", so I guess I'm not the first one to be confused ^)

### CODE REVIEW

**Comment by stormqueen1990** [comment]
Hi there, @VannTen!

Could you please rebase your PR? It appears we had a linting issue on `master` that is causing your PR to fail the lint check.

**Review by stormqueen1990 — COMMENTED** [review]
/lgtm

/assign @koba1t 
for maintainer review

**Comment by koba1t** [comment]
Thanks @VannTen 
/approve

**Pull request merged**
