### PR TITLE
Filesys default

### PR DESCRIPTION
**Pull request by campoy**
Updates #3873

This PR adds a type that satisfies `filesys.FileSystem` by forwarding all the method calls to its given `FileSystem` field.
If the field is nil, the call will be done on the result of calling `MakeFsOnDisk`.

This type will simplify how other structs expose a `FileSystem` interface as the zero value for the type already performs the expected behavior of talking to the real disk, without having to add `if v.FileSystem == nil { ... }` all across the codebase.

### CODE REVIEW

**Comment by natasha41575** [comment]
/ok-to-test

Thanks for working on this!

**Comment by campoy** [comment]
I'm not sure why this failed now. It sounds like a flake by the linter?

**Comment by natasha41575** [comment]
@KnVerey could you take a look?

To me it seems a bit much to create a whole new type that delegates everything to the underlying structure just for the sake of the `if v.FileSystem == nil` check. Are there any alternatives?

**Comment by natasha41575** [comment]
I'm not sure it makes sense to add a whole new type that delegates to the underlying structure just for the `== nil` check.

Suggest an alternative: add an FS() method to `kio.LocalPackageReadWriter`, `kio.LocalPackageReader`, or `kio.LocalPackageWriter`, and keep their fileSys variable private. Then, `kioLocalPackageReadWriter.FS()` can return the default if it's nil. Thoughts?

**Comment by campoy** [comment]
This is actually going to be in more than just `kio.LocalPackage(Read|Writer)`, since it also needs to go into all the types they use that hit the filesystem such as `kio.ignoreFileMatcher`.

I think it's fine for now to add the type as an unexpected type in `kio`, but the type does make it much easier to use `filesys.FileSystem` in code that wants to expose the `FileSystem` interface so tests can be written easily without having to handle that many code changes.

Happy to close this PR for now and reconsider later on.

**Comment by natasha41575** [comment]
>  the type does make it much easier to use filesys.FileSystem in code that wants to expose the FileSystem interface so tests can be written easily without having to handle that many code changes

That makes sense to me, I'd say leave the PR open then. @KnVerey could you take a look?

**Comment by monopole** [comment]
/lgtm

nice idea!

**Comment by monopole** [comment]
feel free to squash, .  The commit messages wind up the release notes.
Not a bad idea to have a commit that just does the go.sum updates, but also not required.

**Pull request merged**
